// Generated by dedot cli

import type { GenericChainErrors, GenericPalletError } from "dedot/types";

export interface ChainErrors extends GenericChainErrors {
  /**
   * Pallet `System`'s errors
   **/
  system: {
    /**
     * The name of specification does not match between the current runtime
     * and the new runtime.
     **/
    InvalidSpecName: GenericPalletError;

    /**
     * The specification version is not allowed to decrease between the current runtime
     * and the new runtime.
     **/
    SpecVersionNeedsToIncrease: GenericPalletError;

    /**
     * Failed to extract the runtime version from the new runtime.
     *
     * Either calling `Core_version` or decoding `RuntimeVersion` failed.
     **/
    FailedToExtractRuntimeVersion: GenericPalletError;

    /**
     * Suicide called when the account has non-default composite data.
     **/
    NonDefaultComposite: GenericPalletError;

    /**
     * There is a non-zero reference count preventing the account from being purged.
     **/
    NonZeroRefCount: GenericPalletError;

    /**
     * The origin filter prevent the call to be dispatched.
     **/
    CallFiltered: GenericPalletError;

    /**
     * A multi-block migration is ongoing and prevents the current code from being replaced.
     **/
    MultiBlockMigrationsOngoing: GenericPalletError;

    /**
     * No upgrade authorized.
     **/
    NothingAuthorized: GenericPalletError;

    /**
     * The submitted code is not authorized.
     **/
    Unauthorized: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `ParachainSystem`'s errors
   **/
  parachainSystem: {
    /**
     * Attempt to upgrade validation function while existing upgrade pending.
     **/
    OverlappingUpgrades: GenericPalletError;

    /**
     * Polkadot currently prohibits this parachain from upgrading its validation function.
     **/
    ProhibitedByPolkadot: GenericPalletError;

    /**
     * The supplied validation function has compiled into a blob larger than Polkadot is
     * willing to run.
     **/
    TooBig: GenericPalletError;

    /**
     * The inherent which supplies the validation data did not run this block.
     **/
    ValidationDataNotAvailable: GenericPalletError;

    /**
     * The inherent which supplies the host configuration did not run this block.
     **/
    HostConfigurationNotAvailable: GenericPalletError;

    /**
     * No validation function upgrade is currently scheduled.
     **/
    NotScheduled: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Balances`'s errors
   **/
  balances: {
    /**
     * Vesting balance too high to send value.
     **/
    VestingBalance: GenericPalletError;

    /**
     * Account liquidity restrictions prevent withdrawal.
     **/
    LiquidityRestrictions: GenericPalletError;

    /**
     * Balance too low to send value.
     **/
    InsufficientBalance: GenericPalletError;

    /**
     * Value too low to create account due to existential deposit.
     **/
    ExistentialDeposit: GenericPalletError;

    /**
     * Transfer/payment would kill account.
     **/
    Expendability: GenericPalletError;

    /**
     * A vesting schedule already exists for this account.
     **/
    ExistingVestingSchedule: GenericPalletError;

    /**
     * Beneficiary account must pre-exist.
     **/
    DeadAccount: GenericPalletError;

    /**
     * Number of named reserves exceed `MaxReserves`.
     **/
    TooManyReserves: GenericPalletError;

    /**
     * Number of holds exceed `VariantCountOf<T::RuntimeHoldReason>`.
     **/
    TooManyHolds: GenericPalletError;

    /**
     * Number of freezes exceed `MaxFreezes`.
     **/
    TooManyFreezes: GenericPalletError;

    /**
     * The issuance cannot be modified since it is already deactivated.
     **/
    IssuanceDeactivated: GenericPalletError;

    /**
     * The delta cannot be zero.
     **/
    DeltaZero: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Sudo`'s errors
   **/
  sudo: {
    /**
     * Sender must be the Sudo account.
     **/
    RequireSudo: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Utility`'s errors
   **/
  utility: {
    /**
     * Too many calls batched.
     **/
    TooManyCalls: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `CollatorSelection`'s errors
   **/
  collatorSelection: {
    /**
     * The pallet has too many candidates.
     **/
    TooManyCandidates: GenericPalletError;

    /**
     * Leaving would result in too few candidates.
     **/
    TooFewEligibleCollators: GenericPalletError;

    /**
     * Account is already a candidate.
     **/
    AlreadyCandidate: GenericPalletError;

    /**
     * Account is not a candidate.
     **/
    NotCandidate: GenericPalletError;

    /**
     * There are too many Invulnerables.
     **/
    TooManyInvulnerables: GenericPalletError;

    /**
     * Account is already an Invulnerable.
     **/
    AlreadyInvulnerable: GenericPalletError;

    /**
     * Account is not an Invulnerable.
     **/
    NotInvulnerable: GenericPalletError;

    /**
     * Account has no associated validator ID.
     **/
    NoAssociatedValidatorId: GenericPalletError;

    /**
     * Validator ID is not yet registered.
     **/
    ValidatorNotRegistered: GenericPalletError;

    /**
     * Could not insert in the candidate list.
     **/
    InsertToCandidateListFailed: GenericPalletError;

    /**
     * Could not remove from the candidate list.
     **/
    RemoveFromCandidateListFailed: GenericPalletError;

    /**
     * New deposit amount would be below the minimum candidacy bond.
     **/
    DepositTooLow: GenericPalletError;

    /**
     * Could not update the candidate list.
     **/
    UpdateCandidateListFailed: GenericPalletError;

    /**
     * Deposit amount is too low to take the target's slot in the candidate list.
     **/
    InsufficientBond: GenericPalletError;

    /**
     * The target account to be replaced in the candidate list is not a candidate.
     **/
    TargetIsNotCandidate: GenericPalletError;

    /**
     * The updated deposit amount is equal to the amount already reserved.
     **/
    IdenticalDeposit: GenericPalletError;

    /**
     * Cannot lower candidacy bond while occupying a future collator slot in the list.
     **/
    InvalidUnreserve: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Session`'s errors
   **/
  session: {
    /**
     * Invalid ownership proof.
     **/
    InvalidProof: GenericPalletError;

    /**
     * No associated validator ID for account.
     **/
    NoAssociatedValidatorId: GenericPalletError;

    /**
     * Registered duplicate key.
     **/
    DuplicatedKey: GenericPalletError;

    /**
     * No keys are associated with this account.
     **/
    NoKeys: GenericPalletError;

    /**
     * Key setting account is not live, so it's impossible to associate keys.
     **/
    NoAccount: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `XcmpQueue`'s errors
   **/
  xcmpQueue: {
    /**
     * Setting the queue config failed since one of its values was invalid.
     **/
    BadQueueConfig: GenericPalletError;

    /**
     * The execution is already suspended.
     **/
    AlreadySuspended: GenericPalletError;

    /**
     * The execution is already resumed.
     **/
    AlreadyResumed: GenericPalletError;

    /**
     * There are too many active outbound channels.
     **/
    TooManyActiveOutboundChannels: GenericPalletError;

    /**
     * The message is too big.
     **/
    TooBig: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `PolkadotXcm`'s errors
   **/
  polkadotXcm: {
    /**
     * The desired destination was unreachable, generally because there is a no way of routing
     * to it.
     **/
    Unreachable: GenericPalletError;

    /**
     * There was some other issue (i.e. not to do with routing) in sending the message.
     * Perhaps a lack of space for buffering the message.
     **/
    SendFailure: GenericPalletError;

    /**
     * The message execution fails the filter.
     **/
    Filtered: GenericPalletError;

    /**
     * The message's weight could not be determined.
     **/
    UnweighableMessage: GenericPalletError;

    /**
     * The destination `Location` provided cannot be inverted.
     **/
    DestinationNotInvertible: GenericPalletError;

    /**
     * The assets to be sent are empty.
     **/
    Empty: GenericPalletError;

    /**
     * Could not re-anchor the assets to declare the fees for the destination chain.
     **/
    CannotReanchor: GenericPalletError;

    /**
     * Too many assets have been attempted for transfer.
     **/
    TooManyAssets: GenericPalletError;

    /**
     * Origin is invalid for sending.
     **/
    InvalidOrigin: GenericPalletError;

    /**
     * The version of the `Versioned` value used is not able to be interpreted.
     **/
    BadVersion: GenericPalletError;

    /**
     * The given location could not be used (e.g. because it cannot be expressed in the
     * desired version of XCM).
     **/
    BadLocation: GenericPalletError;

    /**
     * The referenced subscription could not be found.
     **/
    NoSubscription: GenericPalletError;

    /**
     * The location is invalid since it already has a subscription from us.
     **/
    AlreadySubscribed: GenericPalletError;

    /**
     * Could not check-out the assets for teleportation to the destination chain.
     **/
    CannotCheckOutTeleport: GenericPalletError;

    /**
     * The owner does not own (all) of the asset that they wish to do the operation on.
     **/
    LowBalance: GenericPalletError;

    /**
     * The asset owner has too many locks on the asset.
     **/
    TooManyLocks: GenericPalletError;

    /**
     * The given account is not an identifiable sovereign account for any location.
     **/
    AccountNotSovereign: GenericPalletError;

    /**
     * The operation required fees to be paid which the initiator could not meet.
     **/
    FeesNotMet: GenericPalletError;

    /**
     * A remote lock with the corresponding data could not be found.
     **/
    LockNotFound: GenericPalletError;

    /**
     * The unlock operation cannot succeed because there are still consumers of the lock.
     **/
    InUse: GenericPalletError;

    /**
     * Invalid asset, reserve chain could not be determined for it.
     **/
    InvalidAssetUnknownReserve: GenericPalletError;

    /**
     * Invalid asset, do not support remote asset reserves with different fees reserves.
     **/
    InvalidAssetUnsupportedReserve: GenericPalletError;

    /**
     * Too many assets with different reserve locations have been attempted for transfer.
     **/
    TooManyReserves: GenericPalletError;

    /**
     * Local XCM execution incomplete.
     **/
    LocalExecutionIncomplete: GenericPalletError;

    /**
     * Too many locations authorized to alias origin.
     *
     * @deprecated Use `LocalExecutionIncompleteWithError` instead (since 20.0.0)
     **/
    TooManyAuthorizedAliases: GenericPalletError;

    /**
     * Expiry block number is in the past.
     **/
    ExpiresInPast: GenericPalletError;

    /**
     * The alias to remove authorization for was not found.
     **/
    AliasNotFound: GenericPalletError;

    /**
     * Local XCM execution incomplete with the actual XCM error and the index of the
     * instruction that caused the error.
     **/
    LocalExecutionIncompleteWithError: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `MessageQueue`'s errors
   **/
  messageQueue: {
    /**
     * Page is not reapable because it has items remaining to be processed and is not old
     * enough.
     **/
    NotReapable: GenericPalletError;

    /**
     * Page to be reaped does not exist.
     **/
    NoPage: GenericPalletError;

    /**
     * The referenced message could not be found.
     **/
    NoMessage: GenericPalletError;

    /**
     * The message was already processed and cannot be processed again.
     **/
    AlreadyProcessed: GenericPalletError;

    /**
     * The message is queued for future execution.
     **/
    Queued: GenericPalletError;

    /**
     * There is temporarily not enough weight to continue servicing messages.
     **/
    InsufficientWeight: GenericPalletError;

    /**
     * This message is temporarily unprocessable.
     *
     * Such errors are expected, but not guaranteed, to resolve themselves eventually through
     * retrying.
     **/
    TemporarilyUnprocessable: GenericPalletError;

    /**
     * The queue is paused and no message can be executed from it.
     *
     * This can change at any time and may resolve in the future by re-trying.
     **/
    QueuePaused: GenericPalletError;

    /**
     * Another call is in progress and needs to finish before this call can happen.
     **/
    RecursiveDisallowed: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `TemplatePallet`'s errors
   **/
  templatePallet: {
    /**
     * Error names should be descriptive.
     **/
    NoneValue: GenericPalletError;

    /**
     * Errors should have helpful documentation associated with them.
     **/
    StorageOverflow: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Keyword`'s errors
   **/
  keyword: {
    AlreadyRegistered: GenericPalletError;
    UnknownKeyword: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Skill`'s errors
   **/
  skill: {
    AlreadyRegistered: GenericPalletError;
    UnknownSkill: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Faction`'s errors
   **/
  faction: {
    AlreadyRegistered: GenericPalletError;
    UnknownFaction: GenericPalletError;
    ParentNotFound: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Battlekit`'s errors
   **/
  battlekit: {
    AlreadyRegistered: GenericPalletError;
    UnknownItem: GenericPalletError;
    UnknownKeyword: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Armoury`'s errors
   **/
  armoury: {
    FactionNotFound: GenericPalletError;
    ItemNotFound: GenericPalletError;
    AlreadyInArmoury: GenericPalletError;
    NotInArmoury: GenericPalletError;
    ArmouryFull: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Entry`'s errors
   **/
  entry: {
    AlreadyRegistered: GenericPalletError;
    UnknownEntry: GenericPalletError;
    FactionNotFound: GenericPalletError;
    TooManyEntriesForFaction: GenericPalletError;
    TooManyAbilities: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Patron`'s errors
   **/
  patron: {
    AlreadyRegistered: GenericPalletError;
    UnknownPatron: GenericPalletError;
    UnknownSkill: GenericPalletError;
    UnknownFaction: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Warband`'s errors
   **/
  warband: {
    FactionNotFound: GenericPalletError;
    PatronNotFound: GenericPalletError;
    PatronFactionMismatch: GenericPalletError;
    NotOwner: GenericPalletError;
    WarbandNotFound: GenericPalletError;
    TooManyWarbands: GenericPalletError;
    AlreadyInCampaign: GenericPalletError;
    NotInCampaign: GenericPalletError;
    WarbandLocked: GenericPalletError;
    CampaignNotFound: GenericPalletError;
    CampaignEnrollFailed: GenericPalletError;
    CampaignWithdrawFailed: GenericPalletError;
    TooManyExplorationSkills: GenericPalletError;
    RosterIncomplete: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Roster`'s errors
   **/
  roster: {
    WarbandNotFound: GenericPalletError;
    NotOwner: GenericPalletError;
    RosterFull: GenericPalletError;
    SlotOutOfBounds: GenericPalletError;
    EntryNotFound: GenericPalletError;
    FactionMismatch: GenericPalletError;
    InsufficientDucats: GenericPalletError;
    InsufficientGlory: GenericPalletError;
    ItemNotInArmoury: GenericPalletError;
    MaxCountExceeded: GenericPalletError;
    ItemSlotFull: GenericPalletError;
    ItemNotEquipped: GenericPalletError;
    MaxBattleScars: GenericPalletError;
    AlreadyElite: GenericPalletError;
    EliteLimitReached: GenericPalletError;
    SkillSlotFull: GenericPalletError;
    SlotLimitExceeded: GenericPalletError;
    HandSlotsFull: GenericPalletError;
    TagRestriction: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Campaign`'s errors
   **/
  campaign: {
    CampaignNotFound: GenericPalletError;
    NotCreator: GenericPalletError;
    CampaignFull: GenericPalletError;
    InvalidStatus: GenericPalletError;
    AlreadyEnrolled: GenericPalletError;
    NotEnrolled: GenericPalletError;
    WarbandNotFound: GenericPalletError;
    TheatreNotFound: GenericPalletError;
    AlreadyEliminated: GenericPalletError;
    NoVictoryYet: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Battle`'s errors
   **/
  battle: {
    WarbandNotFound: GenericPalletError;
    NotOwner: GenericPalletError;
    WarbandLocked: GenericPalletError;
    CampaignNotFound: GenericPalletError;
    NotEnrolled: GenericPalletError;
    BattleNotFound: GenericPalletError;
    InvalidStatus: GenericPalletError;
    AlreadyInBattle: GenericPalletError;
    ChallengerCannotDefend: GenericPalletError;
    AlreadyReported: GenericPalletError;
    NotParticipant: GenericPalletError;
    MissingReports: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Territory`'s errors
   **/
  territory: {
    TerritoryNotFound: GenericPalletError;
    TerritoryAlreadyExists: GenericPalletError;
    BuildingsFull: GenericPalletError;
    UnknownBuilding: GenericPalletError;
    InsufficientDucats: GenericPalletError;
    NotOwner: GenericPalletError;
    WarbandNotFound: GenericPalletError;
    NotController: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Building`'s errors
   **/
  building: {
    AlreadyRegistered: GenericPalletError;
    UnknownBuilding: GenericPalletError;
    ResourceAlreadyRegistered: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Exploration`'s errors
   **/
  exploration: {
    WarbandNotFound: GenericPalletError;
    NotOwner: GenericPalletError;
    AlreadyExplored: GenericPalletError;
    NoExplorationResult: GenericPalletError;
    OptionAlreadyChosen: GenericPalletError;
    InvalidOption: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Tile`'s errors
   **/
  tile: {
    AlreadyRegistered: GenericPalletError;
    TileNotFound: GenericPalletError;
    BatchTooLarge: GenericPalletError;
    TerrainAlreadyRegistered: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Region`'s errors
   **/
  region: {
    AlreadyRegistered: GenericPalletError;
    RegionNotFound: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Country`'s errors
   **/
  country: {
    AlreadyRegistered: GenericPalletError;
    CountryNotFound: GenericPalletError;
    RegionAlreadyInCountry: GenericPalletError;
    RegionNotInCountry: GenericPalletError;
    TooManyRegions: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Poi`'s errors
   **/
  poi: {
    AlreadyRegistered: GenericPalletError;
    PoiNotFound: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Theatre`'s errors
   **/
  theatre: {
    TheatreAlreadyExists: GenericPalletError;
    TheatreNotFound: GenericPalletError;
    NoRegionsProvided: GenericPalletError;
    TooManyRegions: GenericPalletError;
    TooManySecondaryObjectives: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Equiprules`'s errors
   **/
  equiprules: {
    AlreadyRegistered: GenericPalletError;
    UnknownTag: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `CampaignRules`'s errors
   **/
  campaignRules: {
    TableTooLarge: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `ExplorationRules`'s errors
   **/
  explorationRules: {
    AlreadyRegistered: GenericPalletError;
    UnknownEvent: GenericPalletError;
    UnknownSkill: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `TerrainRules`'s errors
   **/
  terrainRules: {
    UnknownCategory: GenericPalletError;
    UnknownPiece: GenericPalletError;
    UnknownArchetype: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Production`'s errors
   **/
  production: {
    TileFull: GenericPalletError;
    BuildingNotFound: GenericPalletError;
    MaxLevelReached: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Logistics`'s errors
   **/
  logistics: {
    NoPath: GenericPalletError;
    TooManyRegions: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
}
