// Generated by dedot cli

import type { GenericChainEvents, GenericPalletEvent } from "dedot/types";
import type {
  DispatchError,
  AccountId32,
  H256,
  FixedBytes,
  Result,
} from "dedot/codecs";
import type {
  FrameSystemDispatchEventInfo,
  SpWeightsWeightV2Weight,
  FrameSupportTokensMiscBalanceStatus,
  ParachainTemplateRuntimeRuntimeHoldReason,
  PalletBalancesUnexpectedKind,
  StagingXcmV5TraitsOutcome,
  StagingXcmV5Location,
  StagingXcmV5Xcm,
  XcmV3TraitsSendError,
  XcmV5TraitsError,
  StagingXcmV5Response,
  XcmVersionedAssets,
  StagingXcmV5AssetAssets,
  XcmVersionedLocation,
  CumulusPrimitivesCoreAggregateMessageOrigin,
  FrameSupportMessagesProcessMessageError,
  TcPrimitivesKeywordKind,
  TcPrimitivesAlignment,
  TcPrimitivesBattlekitType,
  TcPrimitivesCostType,
  TcPrimitivesObjectiveVpReason,
  TcPrimitivesRegionControl,
  TcPrimitivesExplorationTable,
} from "./types.js";

export interface ChainEvents extends GenericChainEvents {
  /**
   * Pallet `System`'s events
   **/
  system: {
    /**
     * An extrinsic completed successfully.
     **/
    ExtrinsicSuccess: GenericPalletEvent<
      "System",
      "ExtrinsicSuccess",
      { dispatchInfo: FrameSystemDispatchEventInfo }
    >;

    /**
     * An extrinsic failed.
     **/
    ExtrinsicFailed: GenericPalletEvent<
      "System",
      "ExtrinsicFailed",
      {
        dispatchError: DispatchError;
        dispatchInfo: FrameSystemDispatchEventInfo;
      }
    >;

    /**
     * `:code` was updated.
     **/
    CodeUpdated: GenericPalletEvent<"System", "CodeUpdated", null>;

    /**
     * A new account was created.
     **/
    NewAccount: GenericPalletEvent<
      "System",
      "NewAccount",
      { account: AccountId32 }
    >;

    /**
     * An account was reaped.
     **/
    KilledAccount: GenericPalletEvent<
      "System",
      "KilledAccount",
      { account: AccountId32 }
    >;

    /**
     * On on-chain remark happened.
     **/
    Remarked: GenericPalletEvent<
      "System",
      "Remarked",
      { sender: AccountId32; hash: H256 }
    >;

    /**
     * An upgrade was authorized.
     **/
    UpgradeAuthorized: GenericPalletEvent<
      "System",
      "UpgradeAuthorized",
      { codeHash: H256; checkVersion: boolean }
    >;

    /**
     * An invalid authorized upgrade was rejected while trying to apply it.
     **/
    RejectedInvalidAuthorizedUpgrade: GenericPalletEvent<
      "System",
      "RejectedInvalidAuthorizedUpgrade",
      { codeHash: H256; error: DispatchError }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `ParachainSystem`'s events
   **/
  parachainSystem: {
    /**
     * The validation function has been scheduled to apply.
     **/
    ValidationFunctionStored: GenericPalletEvent<
      "ParachainSystem",
      "ValidationFunctionStored",
      null
    >;

    /**
     * The validation function was applied as of the contained relay chain block number.
     **/
    ValidationFunctionApplied: GenericPalletEvent<
      "ParachainSystem",
      "ValidationFunctionApplied",
      { relayChainBlockNum: number }
    >;

    /**
     * The relay-chain aborted the upgrade process.
     **/
    ValidationFunctionDiscarded: GenericPalletEvent<
      "ParachainSystem",
      "ValidationFunctionDiscarded",
      null
    >;

    /**
     * Some downward messages have been received and will be processed.
     **/
    DownwardMessagesReceived: GenericPalletEvent<
      "ParachainSystem",
      "DownwardMessagesReceived",
      { count: number }
    >;

    /**
     * Downward messages were processed using the given weight.
     **/
    DownwardMessagesProcessed: GenericPalletEvent<
      "ParachainSystem",
      "DownwardMessagesProcessed",
      { weightUsed: SpWeightsWeightV2Weight; dmqHead: H256 }
    >;

    /**
     * An upward message was sent to the relay chain.
     **/
    UpwardMessageSent: GenericPalletEvent<
      "ParachainSystem",
      "UpwardMessageSent",
      { messageHash?: FixedBytes<32> | undefined }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Balances`'s events
   **/
  balances: {
    /**
     * An account was created with some free balance.
     **/
    Endowed: GenericPalletEvent<
      "Balances",
      "Endowed",
      { account: AccountId32; freeBalance: bigint }
    >;

    /**
     * An account was removed whose balance was non-zero but below ExistentialDeposit,
     * resulting in an outright loss.
     **/
    DustLost: GenericPalletEvent<
      "Balances",
      "DustLost",
      { account: AccountId32; amount: bigint }
    >;

    /**
     * Transfer succeeded.
     **/
    Transfer: GenericPalletEvent<
      "Balances",
      "Transfer",
      { from: AccountId32; to: AccountId32; amount: bigint }
    >;

    /**
     * A balance was set by root.
     **/
    BalanceSet: GenericPalletEvent<
      "Balances",
      "BalanceSet",
      { who: AccountId32; free: bigint }
    >;

    /**
     * Some balance was reserved (moved from free to reserved).
     **/
    Reserved: GenericPalletEvent<
      "Balances",
      "Reserved",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some balance was unreserved (moved from reserved to free).
     **/
    Unreserved: GenericPalletEvent<
      "Balances",
      "Unreserved",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some balance was moved from the reserve of the first account to the second account.
     * Final argument indicates the destination balance type.
     **/
    ReserveRepatriated: GenericPalletEvent<
      "Balances",
      "ReserveRepatriated",
      {
        from: AccountId32;
        to: AccountId32;
        amount: bigint;
        destinationStatus: FrameSupportTokensMiscBalanceStatus;
      }
    >;

    /**
     * Some amount was deposited (e.g. for transaction fees).
     **/
    Deposit: GenericPalletEvent<
      "Balances",
      "Deposit",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some amount was withdrawn from the account (e.g. for transaction fees).
     **/
    Withdraw: GenericPalletEvent<
      "Balances",
      "Withdraw",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some amount was removed from the account (e.g. for misbehavior).
     **/
    Slashed: GenericPalletEvent<
      "Balances",
      "Slashed",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some amount was minted into an account.
     **/
    Minted: GenericPalletEvent<
      "Balances",
      "Minted",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some credit was balanced and added to the TotalIssuance.
     **/
    MintedCredit: GenericPalletEvent<
      "Balances",
      "MintedCredit",
      { amount: bigint }
    >;

    /**
     * Some amount was burned from an account.
     **/
    Burned: GenericPalletEvent<
      "Balances",
      "Burned",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some debt has been dropped from the Total Issuance.
     **/
    BurnedDebt: GenericPalletEvent<
      "Balances",
      "BurnedDebt",
      { amount: bigint }
    >;

    /**
     * Some amount was suspended from an account (it can be restored later).
     **/
    Suspended: GenericPalletEvent<
      "Balances",
      "Suspended",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some amount was restored into an account.
     **/
    Restored: GenericPalletEvent<
      "Balances",
      "Restored",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * An account was upgraded.
     **/
    Upgraded: GenericPalletEvent<"Balances", "Upgraded", { who: AccountId32 }>;

    /**
     * Total issuance was increased by `amount`, creating a credit to be balanced.
     **/
    Issued: GenericPalletEvent<"Balances", "Issued", { amount: bigint }>;

    /**
     * Total issuance was decreased by `amount`, creating a debt to be balanced.
     **/
    Rescinded: GenericPalletEvent<"Balances", "Rescinded", { amount: bigint }>;

    /**
     * Some balance was locked.
     **/
    Locked: GenericPalletEvent<
      "Balances",
      "Locked",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some balance was unlocked.
     **/
    Unlocked: GenericPalletEvent<
      "Balances",
      "Unlocked",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some balance was frozen.
     **/
    Frozen: GenericPalletEvent<
      "Balances",
      "Frozen",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * Some balance was thawed.
     **/
    Thawed: GenericPalletEvent<
      "Balances",
      "Thawed",
      { who: AccountId32; amount: bigint }
    >;

    /**
     * The `TotalIssuance` was forcefully changed.
     **/
    TotalIssuanceForced: GenericPalletEvent<
      "Balances",
      "TotalIssuanceForced",
      { old: bigint; new: bigint }
    >;

    /**
     * Some balance was placed on hold.
     **/
    Held: GenericPalletEvent<
      "Balances",
      "Held",
      {
        reason: ParachainTemplateRuntimeRuntimeHoldReason;
        who: AccountId32;
        amount: bigint;
      }
    >;

    /**
     * Held balance was burned from an account.
     **/
    BurnedHeld: GenericPalletEvent<
      "Balances",
      "BurnedHeld",
      {
        reason: ParachainTemplateRuntimeRuntimeHoldReason;
        who: AccountId32;
        amount: bigint;
      }
    >;

    /**
     * A transfer of `amount` on hold from `source` to `dest` was initiated.
     **/
    TransferOnHold: GenericPalletEvent<
      "Balances",
      "TransferOnHold",
      {
        reason: ParachainTemplateRuntimeRuntimeHoldReason;
        source: AccountId32;
        dest: AccountId32;
        amount: bigint;
      }
    >;

    /**
     * The `transferred` balance is placed on hold at the `dest` account.
     **/
    TransferAndHold: GenericPalletEvent<
      "Balances",
      "TransferAndHold",
      {
        reason: ParachainTemplateRuntimeRuntimeHoldReason;
        source: AccountId32;
        dest: AccountId32;
        transferred: bigint;
      }
    >;

    /**
     * Some balance was released from hold.
     **/
    Released: GenericPalletEvent<
      "Balances",
      "Released",
      {
        reason: ParachainTemplateRuntimeRuntimeHoldReason;
        who: AccountId32;
        amount: bigint;
      }
    >;

    /**
     * An unexpected/defensive event was triggered.
     **/
    Unexpected: GenericPalletEvent<
      "Balances",
      "Unexpected",
      PalletBalancesUnexpectedKind
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `TransactionPayment`'s events
   **/
  transactionPayment: {
    /**
     * A transaction fee `actual_fee`, of which `tip` was added to the minimum inclusion fee,
     * has been paid by `who`.
     **/
    TransactionFeePaid: GenericPalletEvent<
      "TransactionPayment",
      "TransactionFeePaid",
      { who: AccountId32; actualFee: bigint; tip: bigint }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Sudo`'s events
   **/
  sudo: {
    /**
     * A sudo call just took place.
     **/
    Sudid: GenericPalletEvent<
      "Sudo",
      "Sudid",
      {
        /**
         * The result of the call made by the sudo user.
         **/
        sudoResult: Result<[], DispatchError>;
      }
    >;

    /**
     * The sudo key has been updated.
     **/
    KeyChanged: GenericPalletEvent<
      "Sudo",
      "KeyChanged",
      {
        /**
         * The old sudo key (if one was previously set).
         **/
        old?: AccountId32 | undefined;

        /**
         * The new sudo key (if one was set).
         **/
        new: AccountId32;
      }
    >;

    /**
     * The key was permanently removed.
     **/
    KeyRemoved: GenericPalletEvent<"Sudo", "KeyRemoved", null>;

    /**
     * A [sudo_as](Pallet::sudo_as) call just took place.
     **/
    SudoAsDone: GenericPalletEvent<
      "Sudo",
      "SudoAsDone",
      {
        /**
         * The result of the call made by the sudo user.
         **/
        sudoResult: Result<[], DispatchError>;
      }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Utility`'s events
   **/
  utility: {
    /**
     * Batch of dispatches did not complete fully. Index of first failing dispatch given, as
     * well as the error.
     **/
    BatchInterrupted: GenericPalletEvent<
      "Utility",
      "BatchInterrupted",
      { index: number; error: DispatchError }
    >;

    /**
     * Batch of dispatches completed fully with no error.
     **/
    BatchCompleted: GenericPalletEvent<"Utility", "BatchCompleted", null>;

    /**
     * Batch of dispatches completed but has errors.
     **/
    BatchCompletedWithErrors: GenericPalletEvent<
      "Utility",
      "BatchCompletedWithErrors",
      null
    >;

    /**
     * A single item within a Batch of dispatches has completed with no error.
     **/
    ItemCompleted: GenericPalletEvent<"Utility", "ItemCompleted", null>;

    /**
     * A single item within a Batch of dispatches has completed with error.
     **/
    ItemFailed: GenericPalletEvent<
      "Utility",
      "ItemFailed",
      { error: DispatchError }
    >;

    /**
     * A call was dispatched.
     **/
    DispatchedAs: GenericPalletEvent<
      "Utility",
      "DispatchedAs",
      { result: Result<[], DispatchError> }
    >;

    /**
     * Main call was dispatched.
     **/
    IfElseMainSuccess: GenericPalletEvent<"Utility", "IfElseMainSuccess", null>;

    /**
     * The fallback call was dispatched.
     **/
    IfElseFallbackCalled: GenericPalletEvent<
      "Utility",
      "IfElseFallbackCalled",
      { mainError: DispatchError }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `CollatorSelection`'s events
   **/
  collatorSelection: {
    /**
     * New Invulnerables were set.
     **/
    NewInvulnerables: GenericPalletEvent<
      "CollatorSelection",
      "NewInvulnerables",
      { invulnerables: Array<AccountId32> }
    >;

    /**
     * A new Invulnerable was added.
     **/
    InvulnerableAdded: GenericPalletEvent<
      "CollatorSelection",
      "InvulnerableAdded",
      { accountId: AccountId32 }
    >;

    /**
     * An Invulnerable was removed.
     **/
    InvulnerableRemoved: GenericPalletEvent<
      "CollatorSelection",
      "InvulnerableRemoved",
      { accountId: AccountId32 }
    >;

    /**
     * The number of desired candidates was set.
     **/
    NewDesiredCandidates: GenericPalletEvent<
      "CollatorSelection",
      "NewDesiredCandidates",
      { desiredCandidates: number }
    >;

    /**
     * The candidacy bond was set.
     **/
    NewCandidacyBond: GenericPalletEvent<
      "CollatorSelection",
      "NewCandidacyBond",
      { bondAmount: bigint }
    >;

    /**
     * A new candidate joined.
     **/
    CandidateAdded: GenericPalletEvent<
      "CollatorSelection",
      "CandidateAdded",
      { accountId: AccountId32; deposit: bigint }
    >;

    /**
     * Bond of a candidate updated.
     **/
    CandidateBondUpdated: GenericPalletEvent<
      "CollatorSelection",
      "CandidateBondUpdated",
      { accountId: AccountId32; deposit: bigint }
    >;

    /**
     * A candidate was removed.
     **/
    CandidateRemoved: GenericPalletEvent<
      "CollatorSelection",
      "CandidateRemoved",
      { accountId: AccountId32 }
    >;

    /**
     * An account was replaced in the candidate list by another one.
     **/
    CandidateReplaced: GenericPalletEvent<
      "CollatorSelection",
      "CandidateReplaced",
      { old: AccountId32; new: AccountId32; deposit: bigint }
    >;

    /**
     * An account was unable to be added to the Invulnerables because they did not have keys
     * registered. Other Invulnerables may have been set.
     **/
    InvalidInvulnerableSkipped: GenericPalletEvent<
      "CollatorSelection",
      "InvalidInvulnerableSkipped",
      { accountId: AccountId32 }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Session`'s events
   **/
  session: {
    /**
     * New session has happened. Note that the argument is the session index, not the
     * block number as the type might suggest.
     **/
    NewSession: GenericPalletEvent<
      "Session",
      "NewSession",
      { sessionIndex: number }
    >;

    /**
     * The `NewSession` event in the current block also implies a new validator set to be
     * queued.
     **/
    NewQueued: GenericPalletEvent<"Session", "NewQueued", null>;

    /**
     * Validator has been disabled.
     **/
    ValidatorDisabled: GenericPalletEvent<
      "Session",
      "ValidatorDisabled",
      { validator: AccountId32 }
    >;

    /**
     * Validator has been re-enabled.
     **/
    ValidatorReenabled: GenericPalletEvent<
      "Session",
      "ValidatorReenabled",
      { validator: AccountId32 }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `XcmpQueue`'s events
   **/
  xcmpQueue: {
    /**
     * An HRMP message was sent to a sibling parachain.
     **/
    XcmpMessageSent: GenericPalletEvent<
      "XcmpQueue",
      "XcmpMessageSent",
      { messageHash: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `PolkadotXcm`'s events
   **/
  polkadotXcm: {
    /**
     * Execution of an XCM message was attempted.
     **/
    Attempted: GenericPalletEvent<
      "PolkadotXcm",
      "Attempted",
      { outcome: StagingXcmV5TraitsOutcome }
    >;

    /**
     * An XCM message was sent.
     **/
    Sent: GenericPalletEvent<
      "PolkadotXcm",
      "Sent",
      {
        origin: StagingXcmV5Location;
        destination: StagingXcmV5Location;
        message: StagingXcmV5Xcm;
        messageId: FixedBytes<32>;
      }
    >;

    /**
     * An XCM message failed to send.
     **/
    SendFailed: GenericPalletEvent<
      "PolkadotXcm",
      "SendFailed",
      {
        origin: StagingXcmV5Location;
        destination: StagingXcmV5Location;
        error: XcmV3TraitsSendError;
        messageId: FixedBytes<32>;
      }
    >;

    /**
     * An XCM message failed to process.
     **/
    ProcessXcmError: GenericPalletEvent<
      "PolkadotXcm",
      "ProcessXcmError",
      {
        origin: StagingXcmV5Location;
        error: XcmV5TraitsError;
        messageId: FixedBytes<32>;
      }
    >;

    /**
     * Query response received which does not match a registered query. This may be because a
     * matching query was never registered, it may be because it is a duplicate response, or
     * because the query timed out.
     **/
    UnexpectedResponse: GenericPalletEvent<
      "PolkadotXcm",
      "UnexpectedResponse",
      { origin: StagingXcmV5Location; queryId: bigint }
    >;

    /**
     * Query response has been received and is ready for taking with `take_response`. There is
     * no registered notification call.
     **/
    ResponseReady: GenericPalletEvent<
      "PolkadotXcm",
      "ResponseReady",
      { queryId: bigint; response: StagingXcmV5Response }
    >;

    /**
     * Query response has been received and query is removed. The registered notification has
     * been dispatched and executed successfully.
     **/
    Notified: GenericPalletEvent<
      "PolkadotXcm",
      "Notified",
      { queryId: bigint; palletIndex: number; callIndex: number }
    >;

    /**
     * Query response has been received and query is removed. The registered notification
     * could not be dispatched because the dispatch weight is greater than the maximum weight
     * originally budgeted by this runtime for the query result.
     **/
    NotifyOverweight: GenericPalletEvent<
      "PolkadotXcm",
      "NotifyOverweight",
      {
        queryId: bigint;
        palletIndex: number;
        callIndex: number;
        actualWeight: SpWeightsWeightV2Weight;
        maxBudgetedWeight: SpWeightsWeightV2Weight;
      }
    >;

    /**
     * Query response has been received and query is removed. There was a general error with
     * dispatching the notification call.
     **/
    NotifyDispatchError: GenericPalletEvent<
      "PolkadotXcm",
      "NotifyDispatchError",
      { queryId: bigint; palletIndex: number; callIndex: number }
    >;

    /**
     * Query response has been received and query is removed. The dispatch was unable to be
     * decoded into a `Call`; this might be due to dispatch function having a signature which
     * is not `(origin, QueryId, Response)`.
     **/
    NotifyDecodeFailed: GenericPalletEvent<
      "PolkadotXcm",
      "NotifyDecodeFailed",
      { queryId: bigint; palletIndex: number; callIndex: number }
    >;

    /**
     * Expected query response has been received but the origin location of the response does
     * not match that expected. The query remains registered for a later, valid, response to
     * be received and acted upon.
     **/
    InvalidResponder: GenericPalletEvent<
      "PolkadotXcm",
      "InvalidResponder",
      {
        origin: StagingXcmV5Location;
        queryId: bigint;
        expectedLocation?: StagingXcmV5Location | undefined;
      }
    >;

    /**
     * Expected query response has been received but the expected origin location placed in
     * storage by this runtime previously cannot be decoded. The query remains registered.
     *
     * This is unexpected (since a location placed in storage in a previously executing
     * runtime should be readable prior to query timeout) and dangerous since the possibly
     * valid response will be dropped. Manual governance intervention is probably going to be
     * needed.
     **/
    InvalidResponderVersion: GenericPalletEvent<
      "PolkadotXcm",
      "InvalidResponderVersion",
      { origin: StagingXcmV5Location; queryId: bigint }
    >;

    /**
     * Received query response has been read and removed.
     **/
    ResponseTaken: GenericPalletEvent<
      "PolkadotXcm",
      "ResponseTaken",
      { queryId: bigint }
    >;

    /**
     * Some assets have been placed in an asset trap.
     **/
    AssetsTrapped: GenericPalletEvent<
      "PolkadotXcm",
      "AssetsTrapped",
      { hash: H256; origin: StagingXcmV5Location; assets: XcmVersionedAssets }
    >;

    /**
     * An XCM version change notification message has been attempted to be sent.
     *
     * The cost of sending it (borne by the chain) is included.
     **/
    VersionChangeNotified: GenericPalletEvent<
      "PolkadotXcm",
      "VersionChangeNotified",
      {
        destination: StagingXcmV5Location;
        result: number;
        cost: StagingXcmV5AssetAssets;
        messageId: FixedBytes<32>;
      }
    >;

    /**
     * The supported version of a location has been changed. This might be through an
     * automatic notification or a manual intervention.
     **/
    SupportedVersionChanged: GenericPalletEvent<
      "PolkadotXcm",
      "SupportedVersionChanged",
      { location: StagingXcmV5Location; version: number }
    >;

    /**
     * A given location which had a version change subscription was dropped owing to an error
     * sending the notification to it.
     **/
    NotifyTargetSendFail: GenericPalletEvent<
      "PolkadotXcm",
      "NotifyTargetSendFail",
      {
        location: StagingXcmV5Location;
        queryId: bigint;
        error: XcmV5TraitsError;
      }
    >;

    /**
     * A given location which had a version change subscription was dropped owing to an error
     * migrating the location to our new XCM format.
     **/
    NotifyTargetMigrationFail: GenericPalletEvent<
      "PolkadotXcm",
      "NotifyTargetMigrationFail",
      { location: XcmVersionedLocation; queryId: bigint }
    >;

    /**
     * Expected query response has been received but the expected querier location placed in
     * storage by this runtime previously cannot be decoded. The query remains registered.
     *
     * This is unexpected (since a location placed in storage in a previously executing
     * runtime should be readable prior to query timeout) and dangerous since the possibly
     * valid response will be dropped. Manual governance intervention is probably going to be
     * needed.
     **/
    InvalidQuerierVersion: GenericPalletEvent<
      "PolkadotXcm",
      "InvalidQuerierVersion",
      { origin: StagingXcmV5Location; queryId: bigint }
    >;

    /**
     * Expected query response has been received but the querier location of the response does
     * not match the expected. The query remains registered for a later, valid, response to
     * be received and acted upon.
     **/
    InvalidQuerier: GenericPalletEvent<
      "PolkadotXcm",
      "InvalidQuerier",
      {
        origin: StagingXcmV5Location;
        queryId: bigint;
        expectedQuerier: StagingXcmV5Location;
        maybeActualQuerier?: StagingXcmV5Location | undefined;
      }
    >;

    /**
     * A remote has requested XCM version change notification from us and we have honored it.
     * A version information message is sent to them and its cost is included.
     **/
    VersionNotifyStarted: GenericPalletEvent<
      "PolkadotXcm",
      "VersionNotifyStarted",
      {
        destination: StagingXcmV5Location;
        cost: StagingXcmV5AssetAssets;
        messageId: FixedBytes<32>;
      }
    >;

    /**
     * We have requested that a remote chain send us XCM version change notifications.
     **/
    VersionNotifyRequested: GenericPalletEvent<
      "PolkadotXcm",
      "VersionNotifyRequested",
      {
        destination: StagingXcmV5Location;
        cost: StagingXcmV5AssetAssets;
        messageId: FixedBytes<32>;
      }
    >;

    /**
     * We have requested that a remote chain stops sending us XCM version change
     * notifications.
     **/
    VersionNotifyUnrequested: GenericPalletEvent<
      "PolkadotXcm",
      "VersionNotifyUnrequested",
      {
        destination: StagingXcmV5Location;
        cost: StagingXcmV5AssetAssets;
        messageId: FixedBytes<32>;
      }
    >;

    /**
     * Fees were paid from a location for an operation (often for using `SendXcm`).
     **/
    FeesPaid: GenericPalletEvent<
      "PolkadotXcm",
      "FeesPaid",
      { paying: StagingXcmV5Location; fees: StagingXcmV5AssetAssets }
    >;

    /**
     * Some assets have been claimed from an asset trap
     **/
    AssetsClaimed: GenericPalletEvent<
      "PolkadotXcm",
      "AssetsClaimed",
      { hash: H256; origin: StagingXcmV5Location; assets: XcmVersionedAssets }
    >;

    /**
     * A XCM version migration finished.
     **/
    VersionMigrationFinished: GenericPalletEvent<
      "PolkadotXcm",
      "VersionMigrationFinished",
      { version: number }
    >;

    /**
     * An `aliaser` location was authorized by `target` to alias it, authorization valid until
     * `expiry` block number.
     **/
    AliasAuthorized: GenericPalletEvent<
      "PolkadotXcm",
      "AliasAuthorized",
      {
        aliaser: StagingXcmV5Location;
        target: StagingXcmV5Location;
        expiry?: bigint | undefined;
      }
    >;

    /**
     * `target` removed alias authorization for `aliaser`.
     **/
    AliasAuthorizationRemoved: GenericPalletEvent<
      "PolkadotXcm",
      "AliasAuthorizationRemoved",
      { aliaser: StagingXcmV5Location; target: StagingXcmV5Location }
    >;

    /**
     * `target` removed all alias authorizations.
     **/
    AliasesAuthorizationsRemoved: GenericPalletEvent<
      "PolkadotXcm",
      "AliasesAuthorizationsRemoved",
      { target: StagingXcmV5Location }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `CumulusXcm`'s events
   **/
  cumulusXcm: {
    /**
     * Downward message is invalid XCM.
     * \[ id \]
     **/
    InvalidFormat: GenericPalletEvent<
      "CumulusXcm",
      "InvalidFormat",
      FixedBytes<32>
    >;

    /**
     * Downward message is unsupported version of XCM.
     * \[ id \]
     **/
    UnsupportedVersion: GenericPalletEvent<
      "CumulusXcm",
      "UnsupportedVersion",
      FixedBytes<32>
    >;

    /**
     * Downward message executed with the given outcome.
     * \[ id, outcome \]
     **/
    ExecutedDownward: GenericPalletEvent<
      "CumulusXcm",
      "ExecutedDownward",
      [FixedBytes<32>, StagingXcmV5TraitsOutcome]
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `MessageQueue`'s events
   **/
  messageQueue: {
    /**
     * Message discarded due to an error in the `MessageProcessor` (usually a format error).
     **/
    ProcessingFailed: GenericPalletEvent<
      "MessageQueue",
      "ProcessingFailed",
      {
        /**
         * The `blake2_256` hash of the message.
         **/
        id: H256;

        /**
         * The queue of the message.
         **/
        origin: CumulusPrimitivesCoreAggregateMessageOrigin;

        /**
         * The error that occurred.
         *
         * This error is pretty opaque. More fine-grained errors need to be emitted as events
         * by the `MessageProcessor`.
         **/
        error: FrameSupportMessagesProcessMessageError;
      }
    >;

    /**
     * Message is processed.
     **/
    Processed: GenericPalletEvent<
      "MessageQueue",
      "Processed",
      {
        /**
         * The `blake2_256` hash of the message.
         **/
        id: H256;

        /**
         * The queue of the message.
         **/
        origin: CumulusPrimitivesCoreAggregateMessageOrigin;

        /**
         * How much weight was used to process the message.
         **/
        weightUsed: SpWeightsWeightV2Weight;

        /**
         * Whether the message was processed.
         *
         * Note that this does not mean that the underlying `MessageProcessor` was internally
         * successful. It *solely* means that the MQ pallet will treat this as a success
         * condition and discard the message. Any internal error needs to be emitted as events
         * by the `MessageProcessor`.
         **/
        success: boolean;
      }
    >;

    /**
     * Message placed in overweight queue.
     **/
    OverweightEnqueued: GenericPalletEvent<
      "MessageQueue",
      "OverweightEnqueued",
      {
        /**
         * The `blake2_256` hash of the message.
         **/
        id: FixedBytes<32>;

        /**
         * The queue of the message.
         **/
        origin: CumulusPrimitivesCoreAggregateMessageOrigin;

        /**
         * The page of the message.
         **/
        pageIndex: number;

        /**
         * The index of the message within the page.
         **/
        messageIndex: number;
      }
    >;

    /**
     * This page was reaped.
     **/
    PageReaped: GenericPalletEvent<
      "MessageQueue",
      "PageReaped",
      {
        /**
         * The queue of the page.
         **/
        origin: CumulusPrimitivesCoreAggregateMessageOrigin;

        /**
         * The index of the page.
         **/
        index: number;
      }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `TemplatePallet`'s events
   **/
  templatePallet: {
    /**
     * We usually use passive tense for events.
     **/
    SomethingStored: GenericPalletEvent<
      "TemplatePallet",
      "SomethingStored",
      { blockNumber: number; who: AccountId32 }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Keyword`'s events
   **/
  keyword: {
    KeywordRegistered: GenericPalletEvent<
      "Keyword",
      "KeywordRegistered",
      { code: FixedBytes<32>; kind: TcPrimitivesKeywordKind }
    >;
    KeywordRemoved: GenericPalletEvent<
      "Keyword",
      "KeywordRemoved",
      { code: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Skill`'s events
   **/
  skill: {
    SkillRegistered: GenericPalletEvent<
      "Skill",
      "SkillRegistered",
      { code: FixedBytes<32> }
    >;
    SkillRemoved: GenericPalletEvent<
      "Skill",
      "SkillRemoved",
      { code: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Faction`'s events
   **/
  faction: {
    FactionRegistered: GenericPalletEvent<
      "Faction",
      "FactionRegistered",
      { code: FixedBytes<16>; alignment: TcPrimitivesAlignment }
    >;
    VariantRegistered: GenericPalletEvent<
      "Faction",
      "VariantRegistered",
      { variant: FixedBytes<16>; parent: FixedBytes<16> }
    >;
    KeywordsUpdated: GenericPalletEvent<
      "Faction",
      "KeywordsUpdated",
      { code: FixedBytes<16> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Battlekit`'s events
   **/
  battlekit: {
    ItemRegistered: GenericPalletEvent<
      "Battlekit",
      "ItemRegistered",
      {
        code: FixedBytes<32>;
        battlekitType: TcPrimitivesBattlekitType;
        cost: number;
      }
    >;
    ItemRemoved: GenericPalletEvent<
      "Battlekit",
      "ItemRemoved",
      { code: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Armoury`'s events
   **/
  armoury: {
    EntryAdded: GenericPalletEvent<
      "Armoury",
      "EntryAdded",
      {
        faction: FixedBytes<16>;
        item: FixedBytes<32>;
        cost: number;
        costType: TcPrimitivesCostType;
      }
    >;
    EntryRemoved: GenericPalletEvent<
      "Armoury",
      "EntryRemoved",
      { faction: FixedBytes<16>; item: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Entry`'s events
   **/
  entry: {
    EntryRegistered: GenericPalletEvent<
      "Entry",
      "EntryRegistered",
      { code: FixedBytes<32>; faction: FixedBytes<16>; cost: number }
    >;
    EntryRemoved: GenericPalletEvent<
      "Entry",
      "EntryRemoved",
      { code: FixedBytes<32>; faction: FixedBytes<16> }
    >;
    AbilitiesSet: GenericPalletEvent<
      "Entry",
      "AbilitiesSet",
      { code: FixedBytes<32>; count: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Patron`'s events
   **/
  patron: {
    PatronRegistered: GenericPalletEvent<
      "Patron",
      "PatronRegistered",
      { code: FixedBytes<32> }
    >;
    PatronRemoved: GenericPalletEvent<
      "Patron",
      "PatronRemoved",
      { code: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Warband`'s events
   **/
  warband: {
    WarbandCreated: GenericPalletEvent<
      "Warband",
      "WarbandCreated",
      { id: number; owner: AccountId32; faction: FixedBytes<16> }
    >;
    WarbandDisbanded: GenericPalletEvent<
      "Warband",
      "WarbandDisbanded",
      { id: number }
    >;
    EnrolledInCampaign: GenericPalletEvent<
      "Warband",
      "EnrolledInCampaign",
      { warbandId: number; campaignId: number }
    >;
    WithdrawnFromCampaign: GenericPalletEvent<
      "Warband",
      "WithdrawnFromCampaign",
      { warbandId: number; campaignId: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Roster`'s events
   **/
  roster: {
    RecruitAdded: GenericPalletEvent<
      "Roster",
      "RecruitAdded",
      { warbandId: number; entryCode: FixedBytes<32>; slot: number }
    >;
    RecruitRemoved: GenericPalletEvent<
      "Roster",
      "RecruitRemoved",
      { warbandId: number; slot: number }
    >;
    ItemEquipped: GenericPalletEvent<
      "Roster",
      "ItemEquipped",
      { warbandId: number; slot: number; item: FixedBytes<32> }
    >;
    ItemUnequipped: GenericPalletEvent<
      "Roster",
      "ItemUnequipped",
      { warbandId: number; slot: number; item: FixedBytes<32> }
    >;
    ItemSold: GenericPalletEvent<
      "Roster",
      "ItemSold",
      { warbandId: number; slot: number; item: FixedBytes<32>; refund: number }
    >;
    XpAdded: GenericPalletEvent<
      "Roster",
      "XpAdded",
      { warbandId: number; slot: number; amount: number }
    >;
    TraumaApplied: GenericPalletEvent<
      "Roster",
      "TraumaApplied",
      { warbandId: number; slot: number; newScars: number }
    >;
    Promoted: GenericPalletEvent<
      "Roster",
      "Promoted",
      { warbandId: number; slot: number }
    >;
    SkillLearned: GenericPalletEvent<
      "Roster",
      "SkillLearned",
      { warbandId: number; slot: number; skill: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Campaign`'s events
   **/
  campaign: {
    CampaignCreated: GenericPalletEvent<
      "Campaign",
      "CampaignCreated",
      { id: number; creator: AccountId32 }
    >;
    CampaignStarted: GenericPalletEvent<
      "Campaign",
      "CampaignStarted",
      { id: number }
    >;
    TurnAdvanced: GenericPalletEvent<
      "Campaign",
      "TurnAdvanced",
      { id: number; turn: number }
    >;
    CampaignConcluded: GenericPalletEvent<
      "Campaign",
      "CampaignConcluded",
      { id: number }
    >;
    WarbandEnrolled: GenericPalletEvent<
      "Campaign",
      "WarbandEnrolled",
      { campaignId: number; warbandId: number; team: number }
    >;
    WarbandWithdrawn: GenericPalletEvent<
      "Campaign",
      "WarbandWithdrawn",
      { campaignId: number; warbandId: number }
    >;
    VpAwarded: GenericPalletEvent<
      "Campaign",
      "VpAwarded",
      {
        campaignId: number;
        warbandId: number;
        amount: number;
        reason: TcPrimitivesObjectiveVpReason;
      }
    >;
    WarbandEliminated: GenericPalletEvent<
      "Campaign",
      "WarbandEliminated",
      { campaignId: number; warbandId: number }
    >;
    VictoryDeclared: GenericPalletEvent<
      "Campaign",
      "VictoryDeclared",
      { campaignId: number; winnerTeam: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Battle`'s events
   **/
  battle: {
    BattleChallenged: GenericPalletEvent<
      "Battle",
      "BattleChallenged",
      {
        battleId: number;
        campaignId: number;
        challenger: number;
        territory: FixedBytes<32>;
      }
    >;
    ChallengeAccepted: GenericPalletEvent<
      "Battle",
      "ChallengeAccepted",
      { battleId: number; defender: number }
    >;
    ReportSubmitted: GenericPalletEvent<
      "Battle",
      "ReportSubmitted",
      { battleId: number; warbandId: number }
    >;
    BattleResolved: GenericPalletEvent<
      "Battle",
      "BattleResolved",
      { battleId: number; winner?: number | undefined }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Territory`'s events
   **/
  territory: {
    TerritoryInitialized: GenericPalletEvent<
      "Territory",
      "TerritoryInitialized",
      { campaignId: number; territory: FixedBytes<32> }
    >;
    TerritoryCaptured: GenericPalletEvent<
      "Territory",
      "TerritoryCaptured",
      { campaignId: number; territory: FixedBytes<32>; warband: number }
    >;
    BuildingConstructed: GenericPalletEvent<
      "Territory",
      "BuildingConstructed",
      {
        campaignId: number;
        territory: FixedBytes<32>;
        building: FixedBytes<32>;
      }
    >;
    BuildingDemolished: GenericPalletEvent<
      "Territory",
      "BuildingDemolished",
      {
        campaignId: number;
        territory: FixedBytes<32>;
        building: FixedBytes<32>;
      }
    >;
    SupplyUpdated: GenericPalletEvent<
      "Territory",
      "SupplyUpdated",
      { campaignId: number; territory: FixedBytes<32>; level: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Building`'s events
   **/
  building: {
    BuildingRegistered: GenericPalletEvent<
      "Building",
      "BuildingRegistered",
      { code: FixedBytes<32> }
    >;
    BuildingRemoved: GenericPalletEvent<
      "Building",
      "BuildingRemoved",
      { code: FixedBytes<32> }
    >;
    ResourceRegistered: GenericPalletEvent<
      "Building",
      "ResourceRegistered",
      { code: FixedBytes<16> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Exploration`'s events
   **/
  exploration: {
    Explored: GenericPalletEvent<
      "Exploration",
      "Explored",
      {
        warbandId: number;
        battleId: number;
        total: number;
        loot: number;
        discovery?: number | undefined;
      }
    >;
    DiscoveryOptionChosen: GenericPalletEvent<
      "Exploration",
      "DiscoveryOptionChosen",
      { warbandId: number; battleId: number; option: number }
    >;
    ExplorationSkillGranted: GenericPalletEvent<
      "Exploration",
      "ExplorationSkillGranted",
      { warbandId: number; skill: FixedBytes<16> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Tile`'s events
   **/
  tile: {
    TileRegistered: GenericPalletEvent<
      "Tile",
      "TileRegistered",
      { coord: [number, number] }
    >;
    TilesBatchRegistered: GenericPalletEvent<
      "Tile",
      "TilesBatchRegistered",
      { count: number }
    >;
    TerrainRegistered: GenericPalletEvent<
      "Tile",
      "TerrainRegistered",
      { id: number }
    >;
    MapConfigSet: GenericPalletEvent<"Tile", "MapConfigSet", null>;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Region`'s events
   **/
  region: {
    RegionRegistered: GenericPalletEvent<
      "Region",
      "RegionRegistered",
      { code: FixedBytes<32> }
    >;
    RegionControlUpdated: GenericPalletEvent<
      "Region",
      "RegionControlUpdated",
      { code: FixedBytes<32>; control: TcPrimitivesRegionControl }
    >;
    TileControlSet: GenericPalletEvent<
      "Region",
      "TileControlSet",
      {
        region: FixedBytes<32>;
        coord: [number, number];
        alignment: TcPrimitivesAlignment;
      }
    >;
    RegionTilesSet: GenericPalletEvent<
      "Region",
      "RegionTilesSet",
      { code: FixedBytes<32>; count: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Country`'s events
   **/
  country: {
    CountryRegistered: GenericPalletEvent<
      "Country",
      "CountryRegistered",
      { code: FixedBytes<32> }
    >;
    RegionAdded: GenericPalletEvent<
      "Country",
      "RegionAdded",
      { country: FixedBytes<32>; region: FixedBytes<32> }
    >;
    RegionRemoved: GenericPalletEvent<
      "Country",
      "RegionRemoved",
      { country: FixedBytes<32>; region: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Poi`'s events
   **/
  poi: {
    PoiRegistered: GenericPalletEvent<
      "Poi",
      "PoiRegistered",
      { code: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Theatre`'s events
   **/
  theatre: {
    TheatreCreated: GenericPalletEvent<
      "Theatre",
      "TheatreCreated",
      { code: FixedBytes<32>; regionCount: number }
    >;
    ObjectivesSet: GenericPalletEvent<
      "Theatre",
      "ObjectivesSet",
      { theatre: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Equiprules`'s events
   **/
  equiprules: {
    SlotRuleSet: GenericPalletEvent<
      "Equiprules",
      "SlotRuleSet",
      { battlekitType: TcPrimitivesBattlekitType }
    >;
    TagRegistered: GenericPalletEvent<
      "Equiprules",
      "TagRegistered",
      { code: FixedBytes<32> }
    >;
    TagRemoved: GenericPalletEvent<
      "Equiprules",
      "TagRemoved",
      { code: FixedBytes<32> }
    >;
    HandSlotsSet: GenericPalletEvent<
      "Equiprules",
      "HandSlotsSet",
      { hands: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `CampaignRules`'s events
   **/
  campaignRules: {
    ThresholdTableSet: GenericPalletEvent<
      "CampaignRules",
      "ThresholdTableSet",
      { count: number }
    >;
    VictoryConfigSet: GenericPalletEvent<
      "CampaignRules",
      "VictoryConfigSet",
      null
    >;
    TraumaTableSet: GenericPalletEvent<
      "CampaignRules",
      "TraumaTableSet",
      { count: number }
    >;
    PhaseStepsSet: GenericPalletEvent<
      "CampaignRules",
      "PhaseStepsSet",
      { count: number }
    >;
    PromotionRulesSet: GenericPalletEvent<
      "CampaignRules",
      "PromotionRulesSet",
      null
    >;
    QuartermasterActionsSet: GenericPalletEvent<
      "CampaignRules",
      "QuartermasterActionsSet",
      { count: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `ExplorationRules`'s events
   **/
  explorationRules: {
    DiceProgressionSet: GenericPalletEvent<
      "ExplorationRules",
      "DiceProgressionSet",
      { count: number }
    >;
    TableProgressionSet: GenericPalletEvent<
      "ExplorationRules",
      "TableProgressionSet",
      { count: number }
    >;
    LootMultiplierSet: GenericPalletEvent<
      "ExplorationRules",
      "LootMultiplierSet",
      { value: number }
    >;
    RerollsSet: GenericPalletEvent<
      "ExplorationRules",
      "RerollsSet",
      { base: number; bonusIfWon: number }
    >;
    ExplorationEventSet: GenericPalletEvent<
      "ExplorationRules",
      "ExplorationEventSet",
      { table: TcPrimitivesExplorationTable; roll: number }
    >;
    ExplorationSkillSet: GenericPalletEvent<
      "ExplorationRules",
      "ExplorationSkillSet",
      { code: FixedBytes<16> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `TerrainRules`'s events
   **/
  terrainRules: {
    CategorySet: GenericPalletEvent<
      "TerrainRules",
      "CategorySet",
      { code: FixedBytes<16> }
    >;
    PieceSet: GenericPalletEvent<
      "TerrainRules",
      "PieceSet",
      { code: FixedBytes<16> }
    >;
    ArchetypeSet: GenericPalletEvent<
      "TerrainRules",
      "ArchetypeSet",
      { code: FixedBytes<16> }
    >;
    TerrainBattlefieldMappingSet: GenericPalletEvent<
      "TerrainRules",
      "TerrainBattlefieldMappingSet",
      { terrain: FixedBytes<16> }
    >;
    CombatModifiersSet: GenericPalletEvent<
      "TerrainRules",
      "CombatModifiersSet",
      null
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Production`'s events
   **/
  production: {
    BuildingPlaced: GenericPalletEvent<
      "Production",
      "BuildingPlaced",
      {
        region: FixedBytes<32>;
        tile: [number, number];
        building: FixedBytes<32>;
        level: number;
      }
    >;
    BuildingUpgraded: GenericPalletEvent<
      "Production",
      "BuildingUpgraded",
      {
        region: FixedBytes<32>;
        tile: [number, number];
        building: FixedBytes<32>;
        newLevel: number;
      }
    >;
    BuildingDemolished: GenericPalletEvent<
      "Production",
      "BuildingDemolished",
      {
        region: FixedBytes<32>;
        tile: [number, number];
        building: FixedBytes<32>;
      }
    >;
    RecipeSeeded: GenericPalletEvent<
      "Production",
      "RecipeSeeded",
      { building: FixedBytes<32> }
    >;
    TerrainYieldSeeded: GenericPalletEvent<
      "Production",
      "TerrainYieldSeeded",
      { terrainId: number }
    >;
    BaseProductionSeeded: GenericPalletEvent<
      "Production",
      "BaseProductionSeeded",
      { region: FixedBytes<32> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Demand`'s events
   **/
  demand: {
    RegionDemandSet: GenericPalletEvent<
      "Demand",
      "RegionDemandSet",
      { region: FixedBytes<32> }
    >;
    FactionBaseDemandSet: GenericPalletEvent<
      "Demand",
      "FactionBaseDemandSet",
      { faction: FixedBytes<16> }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
  /**
   * Pallet `Logistics`'s events
   **/
  logistics: {
    StockUpdated: GenericPalletEvent<
      "Logistics",
      "StockUpdated",
      { region: FixedBytes<32> }
    >;
    PacketCreated: GenericPalletEvent<
      "Logistics",
      "PacketCreated",
      {
        origin: FixedBytes<32>;
        destination: FixedBytes<32>;
        resource: FixedBytes<16>;
        qty: number;
      }
    >;
    PacketDelivered: GenericPalletEvent<
      "Logistics",
      "PacketDelivered",
      { destination: FixedBytes<32>; resource: FixedBytes<16>; qty: number }
    >;
    AdjacencySet: GenericPalletEvent<
      "Logistics",
      "AdjacencySet",
      { region: FixedBytes<32> }
    >;
    DistancesSet: GenericPalletEvent<
      "Logistics",
      "DistancesSet",
      { count: number }
    >;
    MinStockSet: GenericPalletEvent<
      "Logistics",
      "MinStockSet",
      { region: FixedBytes<32>; resource: FixedBytes<16>; threshold: number }
    >;
    RegionsRegistered: GenericPalletEvent<
      "Logistics",
      "RegionsRegistered",
      { count: number }
    >;

    /**
     * Generic pallet event
     **/
    [prop: string]: GenericPalletEvent;
  };
}
