// Generated by dedot cli

import type {
  GenericChainStorage,
  GenericStorageQuery,
  Callback,
} from "dedot/types";
import type {
  AccountId32,
  AccountId32Like,
  H256,
  Bytes,
  Digest,
  Phase,
  FixedU128,
  BytesLike,
  FixedBytes,
} from "dedot/codecs";
import type {
  FrameSystemAccountInfo,
  FrameSupportDispatchPerDispatchClass,
  FrameSystemEventRecord,
  FrameSystemLastRuntimeUpgradeInfo,
  FrameSystemCodeUpgradeAuthorization,
  SpWeightsWeightV2Weight,
  CumulusPalletParachainSystemUnincludedSegmentAncestor,
  CumulusPalletParachainSystemUnincludedSegmentSegmentTracker,
  PolkadotPrimitivesV9PersistedValidationData,
  PolkadotPrimitivesV9UpgradeRestriction,
  PolkadotPrimitivesV9UpgradeGoAhead,
  SpTrieStorageProof,
  CumulusPalletParachainSystemRelayStateSnapshotMessagingStateSnapshot,
  PolkadotPrimitivesV9AbridgedHostConfiguration,
  CumulusPrimitivesParachainInherentMessageQueueChain,
  PolkadotParachainPrimitivesPrimitivesId,
  CumulusPalletParachainSystemParachainInherentInboundMessageId,
  PolkadotCorePrimitivesOutboundHrmpMessage,
  PalletBalancesAccountData,
  PalletBalancesBalanceLock,
  PalletBalancesReserveData,
  FrameSupportTokensMiscIdAmount,
  FrameSupportTokensMiscIdAmountRuntimeFreezeReason,
  PalletTransactionPaymentReleases,
  FrameSupportStorageNoDrop,
  PalletCollatorSelectionCandidateInfo,
  ParachainTemplateRuntimeSessionKeys,
  SpStakingOffenceOffenceSeverity,
  SpCoreCryptoKeyTypeId,
  SpConsensusAuraSr25519AppSr25519Public,
  SpConsensusSlotsSlot,
  CumulusPalletXcmpQueueOutboundChannelDetails,
  CumulusPalletXcmpQueueQueueConfigData,
  PalletXcmQueryStatus,
  XcmVersionedLocation,
  PalletXcmVersionMigrationStage,
  PalletXcmRemoteLockedFungibleRecord,
  XcmVersionedAssetId,
  StagingXcmV5Xcm,
  PalletXcmAuthorizedAliasesEntry,
  PalletMessageQueueBookState,
  CumulusPrimitivesCoreAggregateMessageOrigin,
  PalletMessageQueuePage,
  PalletParachainTemplateCompositeStruct,
  PalletKeywordKeywordRecord,
  PalletSkillSkillRecord,
  PalletFactionFactionRecord,
  PalletBattlekitItemRecord,
  PalletArmouryArmouryEntryDef,
  PalletEntryEntryRecord,
  PalletEntryAbilityDef,
  PalletPatronPatronRecord,
  PalletWarbandWarbandMeta,
  PalletRosterRecruit,
  PalletCampaignCampaignMeta,
  PalletBattleBattleMeta,
  PalletBattleBattleReport,
  PalletTerritoryTerritoryState,
  PalletBuildingBuildingDef,
  PalletBuildingResourceDef,
  PalletExplorationExplorationOutcome,
  PalletTileTileCompact,
  PalletTileTerrainMeta,
  PalletTileMapConfig,
  PalletRegionRegionDef,
  TcPrimitivesAlignment,
  PalletCountryCountryDef,
  PalletPoiPoiDef,
  PalletTheatreTheatreDef,
  PalletTheatreObjectiveSet,
  PalletEquiprulesSlotRule,
  TcPrimitivesBattlekitType,
  PalletEquiprulesTagDef,
  PalletCampaignRulesThresholdRow,
  PalletCampaignRulesVictoryConfig,
  PalletCampaignRulesTraumaRow,
  PalletCampaignRulesPhaseStep,
  PalletCampaignRulesPromotionRules,
  PalletCampaignRulesQuartermasterAction,
  PalletExplorationRulesDiceProgressionRow,
  PalletExplorationRulesTableProgressionRow,
  PalletExplorationRulesExplorationEvent,
  TcPrimitivesExplorationTable,
  PalletExplorationRulesExplorationSkillDef,
  PalletTerrainRulesTerrainCategory,
  PalletTerrainRulesTerrainPiece,
  PalletTerrainRulesBattlefieldArchetype,
  PalletTerrainRulesCombatModifierConfig,
  PalletProductionRecipeStorage,
  PalletLogisticsPacket,
} from "./types.js";

export interface ChainStorage extends GenericChainStorage {
  /**
   * Pallet `System`'s storage queries
   **/
  system: {
    /**
     * The full account information for a particular account ID.
     *
     * @param {AccountId32Like} arg
     * @param {Callback<FrameSystemAccountInfo> =} callback
     **/
    account: GenericStorageQuery<
      (arg: AccountId32Like) => FrameSystemAccountInfo,
      AccountId32
    >;

    /**
     * Total extrinsics count for the current block.
     *
     * @param {Callback<number | undefined> =} callback
     **/
    extrinsicCount: GenericStorageQuery<() => number | undefined>;

    /**
     * Whether all inherents have been applied.
     *
     * @param {Callback<boolean> =} callback
     **/
    inherentsApplied: GenericStorageQuery<() => boolean>;

    /**
     * The current weight for the block.
     *
     * @param {Callback<FrameSupportDispatchPerDispatchClass> =} callback
     **/
    blockWeight: GenericStorageQuery<
      () => FrameSupportDispatchPerDispatchClass
    >;

    /**
     * Total length (in bytes) for all extrinsics put together, for the current block.
     *
     * @param {Callback<number | undefined> =} callback
     **/
    allExtrinsicsLen: GenericStorageQuery<() => number | undefined>;

    /**
     * Map of block numbers to block hashes.
     *
     * @param {number} arg
     * @param {Callback<H256> =} callback
     **/
    blockHash: GenericStorageQuery<(arg: number) => H256, number>;

    /**
     * Extrinsics data for the current block (maps an extrinsic's index to its data).
     *
     * @param {number} arg
     * @param {Callback<Bytes> =} callback
     **/
    extrinsicData: GenericStorageQuery<(arg: number) => Bytes, number>;

    /**
     * The current block number being processed. Set by `execute_block`.
     *
     * @param {Callback<number> =} callback
     **/
    number: GenericStorageQuery<() => number>;

    /**
     * Hash of the previous block.
     *
     * @param {Callback<H256> =} callback
     **/
    parentHash: GenericStorageQuery<() => H256>;

    /**
     * Digest of the current block, also part of the block header.
     *
     * @param {Callback<Digest> =} callback
     **/
    digest: GenericStorageQuery<() => Digest>;

    /**
     * Events deposited for the current block.
     *
     * NOTE: The item is unbound and should therefore never be read on chain.
     * It could otherwise inflate the PoV size of a block.
     *
     * Events have a large in-memory size. Box the events to not go out-of-memory
     * just in case someone still reads them from within the runtime.
     *
     * @param {Callback<Array<FrameSystemEventRecord>> =} callback
     **/
    events: GenericStorageQuery<() => Array<FrameSystemEventRecord>>;

    /**
     * The number of events in the `Events<T>` list.
     *
     * @param {Callback<number> =} callback
     **/
    eventCount: GenericStorageQuery<() => number>;

    /**
     * Mapping between a topic (represented by T::Hash) and a vector of indexes
     * of events in the `<Events<T>>` list.
     *
     * All topic vectors have deterministic storage locations depending on the topic. This
     * allows light-clients to leverage the changes trie storage tracking mechanism and
     * in case of changes fetch the list of events of interest.
     *
     * The value has the type `(BlockNumberFor<T>, EventIndex)` because if we used only just
     * the `EventIndex` then in case if the topic has the same contents on the next block
     * no notification will be triggered thus the event might be lost.
     *
     * @param {H256} arg
     * @param {Callback<Array<[number, number]>> =} callback
     **/
    eventTopics: GenericStorageQuery<
      (arg: H256) => Array<[number, number]>,
      H256
    >;

    /**
     * Stores the `spec_version` and `spec_name` of when the last runtime upgrade happened.
     *
     * @param {Callback<FrameSystemLastRuntimeUpgradeInfo | undefined> =} callback
     **/
    lastRuntimeUpgrade: GenericStorageQuery<
      () => FrameSystemLastRuntimeUpgradeInfo | undefined
    >;

    /**
     * True if we have upgraded so that `type RefCount` is `u32`. False (default) if not.
     *
     * @param {Callback<boolean> =} callback
     **/
    upgradedToU32RefCount: GenericStorageQuery<() => boolean>;

    /**
     * True if we have upgraded so that AccountInfo contains three types of `RefCount`. False
     * (default) if not.
     *
     * @param {Callback<boolean> =} callback
     **/
    upgradedToTripleRefCount: GenericStorageQuery<() => boolean>;

    /**
     * The execution phase of the block.
     *
     * @param {Callback<Phase | undefined> =} callback
     **/
    executionPhase: GenericStorageQuery<() => Phase | undefined>;

    /**
     * `Some` if a code upgrade has been authorized.
     *
     * @param {Callback<FrameSystemCodeUpgradeAuthorization | undefined> =} callback
     **/
    authorizedUpgrade: GenericStorageQuery<
      () => FrameSystemCodeUpgradeAuthorization | undefined
    >;

    /**
     * The weight reclaimed for the extrinsic.
     *
     * This information is available until the end of the extrinsic execution.
     * More precisely this information is removed in `note_applied_extrinsic`.
     *
     * Logic doing some post dispatch weight reduction must update this storage to avoid duplicate
     * reduction.
     *
     * @param {Callback<SpWeightsWeightV2Weight> =} callback
     **/
    extrinsicWeightReclaimed: GenericStorageQuery<
      () => SpWeightsWeightV2Weight
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `ParachainSystem`'s storage queries
   **/
  parachainSystem: {
    /**
     * Latest included block descendants the runtime accepted. In other words, these are
     * ancestors of the currently executing block which have not been included in the observed
     * relay-chain state.
     *
     * The segment length is limited by the capacity returned from the [`ConsensusHook`] configured
     * in the pallet.
     *
     * @param {Callback<Array<CumulusPalletParachainSystemUnincludedSegmentAncestor>> =} callback
     **/
    unincludedSegment: GenericStorageQuery<
      () => Array<CumulusPalletParachainSystemUnincludedSegmentAncestor>
    >;

    /**
     * Storage field that keeps track of bandwidth used by the unincluded segment along with the
     * latest HRMP watermark. Used for limiting the acceptance of new blocks with
     * respect to relay chain constraints.
     *
     * @param {Callback<CumulusPalletParachainSystemUnincludedSegmentSegmentTracker | undefined> =} callback
     **/
    aggregatedUnincludedSegment: GenericStorageQuery<
      () =>
        | CumulusPalletParachainSystemUnincludedSegmentSegmentTracker
        | undefined
    >;

    /**
     * In case of a scheduled upgrade, this storage field contains the validation code to be
     * applied.
     *
     * As soon as the relay chain gives us the go-ahead signal, we will overwrite the
     * [`:code`][sp_core::storage::well_known_keys::CODE] which will result the next block process
     * with the new validation code. This concludes the upgrade process.
     *
     * @param {Callback<Bytes> =} callback
     **/
    pendingValidationCode: GenericStorageQuery<() => Bytes>;

    /**
     * Validation code that is set by the parachain and is to be communicated to collator and
     * consequently the relay-chain.
     *
     * This will be cleared in `on_initialize` of each new block if no other pallet already set
     * the value.
     *
     * @param {Callback<Bytes | undefined> =} callback
     **/
    newValidationCode: GenericStorageQuery<() => Bytes | undefined>;

    /**
     * The [`PersistedValidationData`] set for this block.
     *
     * This value is expected to be set only once by the [`Pallet::set_validation_data`] inherent.
     *
     * @param {Callback<PolkadotPrimitivesV9PersistedValidationData | undefined> =} callback
     **/
    validationData: GenericStorageQuery<
      () => PolkadotPrimitivesV9PersistedValidationData | undefined
    >;

    /**
     * Were the validation data set to notify the relay chain?
     *
     * @param {Callback<boolean> =} callback
     **/
    didSetValidationCode: GenericStorageQuery<() => boolean>;

    /**
     * The relay chain block number associated with the last parachain block.
     *
     * This is updated in `on_finalize`.
     *
     * @param {Callback<number> =} callback
     **/
    lastRelayChainBlockNumber: GenericStorageQuery<() => number>;

    /**
     * An option which indicates if the relay-chain restricts signalling a validation code upgrade.
     * In other words, if this is `Some` and [`NewValidationCode`] is `Some` then the produced
     * candidate will be invalid.
     *
     * This storage item is a mirror of the corresponding value for the current parachain from the
     * relay-chain. This value is ephemeral which means it doesn't hit the storage. This value is
     * set after the inherent.
     *
     * @param {Callback<PolkadotPrimitivesV9UpgradeRestriction | undefined> =} callback
     **/
    upgradeRestrictionSignal: GenericStorageQuery<
      () => PolkadotPrimitivesV9UpgradeRestriction | undefined
    >;

    /**
     * Optional upgrade go-ahead signal from the relay-chain.
     *
     * This storage item is a mirror of the corresponding value for the current parachain from the
     * relay-chain. This value is ephemeral which means it doesn't hit the storage. This value is
     * set after the inherent.
     *
     * @param {Callback<PolkadotPrimitivesV9UpgradeGoAhead | undefined> =} callback
     **/
    upgradeGoAhead: GenericStorageQuery<
      () => PolkadotPrimitivesV9UpgradeGoAhead | undefined
    >;

    /**
     * The state proof for the last relay parent block.
     *
     * This field is meant to be updated each block with the validation data inherent. Therefore,
     * before processing of the inherent, e.g. in `on_initialize` this data may be stale.
     *
     * This data is also absent from the genesis.
     *
     * @param {Callback<SpTrieStorageProof | undefined> =} callback
     **/
    relayStateProof: GenericStorageQuery<() => SpTrieStorageProof | undefined>;

    /**
     * The snapshot of some state related to messaging relevant to the current parachain as per
     * the relay parent.
     *
     * This field is meant to be updated each block with the validation data inherent. Therefore,
     * before processing of the inherent, e.g. in `on_initialize` this data may be stale.
     *
     * This data is also absent from the genesis.
     *
     * @param {Callback<CumulusPalletParachainSystemRelayStateSnapshotMessagingStateSnapshot | undefined> =} callback
     **/
    relevantMessagingState: GenericStorageQuery<
      () =>
        | CumulusPalletParachainSystemRelayStateSnapshotMessagingStateSnapshot
        | undefined
    >;

    /**
     * The parachain host configuration that was obtained from the relay parent.
     *
     * This field is meant to be updated each block with the validation data inherent. Therefore,
     * before processing of the inherent, e.g. in `on_initialize` this data may be stale.
     *
     * This data is also absent from the genesis.
     *
     * @param {Callback<PolkadotPrimitivesV9AbridgedHostConfiguration | undefined> =} callback
     **/
    hostConfiguration: GenericStorageQuery<
      () => PolkadotPrimitivesV9AbridgedHostConfiguration | undefined
    >;

    /**
     * The last downward message queue chain head we have observed.
     *
     * This value is loaded before and saved after processing inbound downward messages carried
     * by the system inherent.
     *
     * @param {Callback<CumulusPrimitivesParachainInherentMessageQueueChain> =} callback
     **/
    lastDmqMqcHead: GenericStorageQuery<
      () => CumulusPrimitivesParachainInherentMessageQueueChain
    >;

    /**
     * The message queue chain heads we have observed per each channel incoming channel.
     *
     * This value is loaded before and saved after processing inbound downward messages carried
     * by the system inherent.
     *
     * @param {Callback<Array<[PolkadotParachainPrimitivesPrimitivesId, CumulusPrimitivesParachainInherentMessageQueueChain]>> =} callback
     **/
    lastHrmpMqcHeads: GenericStorageQuery<
      () => Array<
        [
          PolkadotParachainPrimitivesPrimitivesId,
          CumulusPrimitivesParachainInherentMessageQueueChain,
        ]
      >
    >;

    /**
     * Number of downward messages processed in a block.
     *
     * This will be cleared in `on_initialize` of each new block.
     *
     * @param {Callback<number> =} callback
     **/
    processedDownwardMessages: GenericStorageQuery<() => number>;

    /**
     * The last processed downward message.
     *
     * We need to keep track of this to filter the messages that have been already processed.
     *
     * @param {Callback<CumulusPalletParachainSystemParachainInherentInboundMessageId | undefined> =} callback
     **/
    lastProcessedDownwardMessage: GenericStorageQuery<
      () =>
        | CumulusPalletParachainSystemParachainInherentInboundMessageId
        | undefined
    >;

    /**
     * HRMP watermark that was set in a block.
     *
     * @param {Callback<number> =} callback
     **/
    hrmpWatermark: GenericStorageQuery<() => number>;

    /**
     * The last processed HRMP message.
     *
     * We need to keep track of this to filter the messages that have been already processed.
     *
     * @param {Callback<CumulusPalletParachainSystemParachainInherentInboundMessageId | undefined> =} callback
     **/
    lastProcessedHrmpMessage: GenericStorageQuery<
      () =>
        | CumulusPalletParachainSystemParachainInherentInboundMessageId
        | undefined
    >;

    /**
     * HRMP messages that were sent in a block.
     *
     * This will be cleared in `on_initialize` of each new block.
     *
     * @param {Callback<Array<PolkadotCorePrimitivesOutboundHrmpMessage>> =} callback
     **/
    hrmpOutboundMessages: GenericStorageQuery<
      () => Array<PolkadotCorePrimitivesOutboundHrmpMessage>
    >;

    /**
     * Upward messages that were sent in a block.
     *
     * This will be cleared in `on_initialize` for each new block.
     *
     * @param {Callback<Array<Bytes>> =} callback
     **/
    upwardMessages: GenericStorageQuery<() => Array<Bytes>>;

    /**
     * Upward messages that are still pending and not yet sent to the relay chain.
     *
     * @param {Callback<Array<Bytes>> =} callback
     **/
    pendingUpwardMessages: GenericStorageQuery<() => Array<Bytes>>;

    /**
     * Upward signals that are still pending and not yet sent to the relay chain.
     *
     * This will be cleared in `on_finalize` for each block.
     *
     * @param {Callback<Array<Bytes>> =} callback
     **/
    pendingUpwardSignals: GenericStorageQuery<() => Array<Bytes>>;

    /**
     * The factor to multiply the base delivery fee by for UMP.
     *
     * @param {Callback<FixedU128> =} callback
     **/
    upwardDeliveryFeeFactor: GenericStorageQuery<() => FixedU128>;

    /**
     * The number of HRMP messages we observed in `on_initialize` and thus used that number for
     * announcing the weight of `on_initialize` and `on_finalize`.
     *
     * @param {Callback<number> =} callback
     **/
    announcedHrmpMessagesPerCandidate: GenericStorageQuery<() => number>;

    /**
     * The weight we reserve at the beginning of the block for processing XCMP messages. This
     * overrides the amount set in the Config trait.
     *
     * @param {Callback<SpWeightsWeightV2Weight | undefined> =} callback
     **/
    reservedXcmpWeightOverride: GenericStorageQuery<
      () => SpWeightsWeightV2Weight | undefined
    >;

    /**
     * The weight we reserve at the beginning of the block for processing DMP messages. This
     * overrides the amount set in the Config trait.
     *
     * @param {Callback<SpWeightsWeightV2Weight | undefined> =} callback
     **/
    reservedDmpWeightOverride: GenericStorageQuery<
      () => SpWeightsWeightV2Weight | undefined
    >;

    /**
     * A custom head data that should be returned as result of `validate_block`.
     *
     * See `Pallet::set_custom_validation_head_data` for more information.
     *
     * @param {Callback<Bytes | undefined> =} callback
     **/
    customValidationHeadData: GenericStorageQuery<() => Bytes | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Timestamp`'s storage queries
   **/
  timestamp: {
    /**
     * The current time for the current block.
     *
     * @param {Callback<bigint> =} callback
     **/
    now: GenericStorageQuery<() => bigint>;

    /**
     * Whether the timestamp has been updated in this block.
     *
     * This value is updated to `true` upon successful submission of a timestamp by a node.
     * It is then checked at the end of each block execution in the `on_finalize` hook.
     *
     * @param {Callback<boolean> =} callback
     **/
    didUpdate: GenericStorageQuery<() => boolean>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `ParachainInfo`'s storage queries
   **/
  parachainInfo: {
    /**
     *
     * @param {Callback<PolkadotParachainPrimitivesPrimitivesId> =} callback
     **/
    parachainId: GenericStorageQuery<
      () => PolkadotParachainPrimitivesPrimitivesId
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Balances`'s storage queries
   **/
  balances: {
    /**
     * The total units issued in the system.
     *
     * @param {Callback<bigint> =} callback
     **/
    totalIssuance: GenericStorageQuery<() => bigint>;

    /**
     * The total units of outstanding deactivated balance in the system.
     *
     * @param {Callback<bigint> =} callback
     **/
    inactiveIssuance: GenericStorageQuery<() => bigint>;

    /**
     * The Balances pallet example of storing the balance of an account.
     *
     * # Example
     *
     * ```nocompile
     * impl pallet_balances::Config for Runtime {
     * type AccountStore = StorageMapShim<Self::Account<Runtime>, frame_system::Provider<Runtime>, AccountId, Self::AccountData<Balance>>
     * }
     * ```
     *
     * You can also store the balance of an account in the `System` pallet.
     *
     * # Example
     *
     * ```nocompile
     * impl pallet_balances::Config for Runtime {
     * type AccountStore = System
     * }
     * ```
     *
     * But this comes with tradeoffs, storing account balances in the system pallet stores
     * `frame_system` data alongside the account data contrary to storing account balances in the
     * `Balances` pallet, which uses a `StorageMap` to store balances data only.
     * NOTE: This is only used in the case that this pallet is used to store balances.
     *
     * @param {AccountId32Like} arg
     * @param {Callback<PalletBalancesAccountData> =} callback
     **/
    account: GenericStorageQuery<
      (arg: AccountId32Like) => PalletBalancesAccountData,
      AccountId32
    >;

    /**
     * Any liquidity locks on some account balances.
     * NOTE: Should only be accessed when setting, changing and freeing a lock.
     *
     * Use of locks is deprecated in favour of freezes. See `https://github.com/paritytech/substrate/pull/12951/`
     *
     * @param {AccountId32Like} arg
     * @param {Callback<Array<PalletBalancesBalanceLock>> =} callback
     **/
    locks: GenericStorageQuery<
      (arg: AccountId32Like) => Array<PalletBalancesBalanceLock>,
      AccountId32
    >;

    /**
     * Named reserves on some account balances.
     *
     * Use of reserves is deprecated in favour of holds. See `https://github.com/paritytech/substrate/pull/12951/`
     *
     * @param {AccountId32Like} arg
     * @param {Callback<Array<PalletBalancesReserveData>> =} callback
     **/
    reserves: GenericStorageQuery<
      (arg: AccountId32Like) => Array<PalletBalancesReserveData>,
      AccountId32
    >;

    /**
     * Holds on account balances.
     *
     * @param {AccountId32Like} arg
     * @param {Callback<Array<FrameSupportTokensMiscIdAmount>> =} callback
     **/
    holds: GenericStorageQuery<
      (arg: AccountId32Like) => Array<FrameSupportTokensMiscIdAmount>,
      AccountId32
    >;

    /**
     * Freeze locks on account balances.
     *
     * @param {AccountId32Like} arg
     * @param {Callback<Array<FrameSupportTokensMiscIdAmountRuntimeFreezeReason>> =} callback
     **/
    freezes: GenericStorageQuery<
      (
        arg: AccountId32Like,
      ) => Array<FrameSupportTokensMiscIdAmountRuntimeFreezeReason>,
      AccountId32
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `TransactionPayment`'s storage queries
   **/
  transactionPayment: {
    /**
     *
     * @param {Callback<FixedU128> =} callback
     **/
    nextFeeMultiplier: GenericStorageQuery<() => FixedU128>;

    /**
     *
     * @param {Callback<PalletTransactionPaymentReleases> =} callback
     **/
    storageVersion: GenericStorageQuery<() => PalletTransactionPaymentReleases>;

    /**
     * The `OnChargeTransaction` stores the withdrawn tx fee here.
     *
     * Use `withdraw_txfee` and `remaining_txfee` to access from outside the crate.
     *
     * @param {Callback<FrameSupportStorageNoDrop | undefined> =} callback
     **/
    txPaymentCredit: GenericStorageQuery<
      () => FrameSupportStorageNoDrop | undefined
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Sudo`'s storage queries
   **/
  sudo: {
    /**
     * The `AccountId` of the sudo key.
     *
     * @param {Callback<AccountId32 | undefined> =} callback
     **/
    key: GenericStorageQuery<() => AccountId32 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Authorship`'s storage queries
   **/
  authorship: {
    /**
     * Author of current block.
     *
     * @param {Callback<AccountId32 | undefined> =} callback
     **/
    author: GenericStorageQuery<() => AccountId32 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `CollatorSelection`'s storage queries
   **/
  collatorSelection: {
    /**
     * The invulnerable, permissioned collators. This list must be sorted.
     *
     * @param {Callback<Array<AccountId32>> =} callback
     **/
    invulnerables: GenericStorageQuery<() => Array<AccountId32>>;

    /**
     * The (community, limited) collation candidates. `Candidates` and `Invulnerables` should be
     * mutually exclusive.
     *
     * This list is sorted in ascending order by deposit and when the deposits are equal, the least
     * recently updated is considered greater.
     *
     * @param {Callback<Array<PalletCollatorSelectionCandidateInfo>> =} callback
     **/
    candidateList: GenericStorageQuery<
      () => Array<PalletCollatorSelectionCandidateInfo>
    >;

    /**
     * Last block authored by collator.
     *
     * @param {AccountId32Like} arg
     * @param {Callback<number> =} callback
     **/
    lastAuthoredBlock: GenericStorageQuery<
      (arg: AccountId32Like) => number,
      AccountId32
    >;

    /**
     * Desired number of candidates.
     *
     * This should ideally always be less than [`Config::MaxCandidates`] for weights to be correct.
     *
     * @param {Callback<number> =} callback
     **/
    desiredCandidates: GenericStorageQuery<() => number>;

    /**
     * Fixed amount to deposit to become a collator.
     *
     * When a collator calls `leave_intent` they immediately receive the deposit back.
     *
     * @param {Callback<bigint> =} callback
     **/
    candidacyBond: GenericStorageQuery<() => bigint>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Session`'s storage queries
   **/
  session: {
    /**
     * The current set of validators.
     *
     * @param {Callback<Array<AccountId32>> =} callback
     **/
    validators: GenericStorageQuery<() => Array<AccountId32>>;

    /**
     * Current index of the session.
     *
     * @param {Callback<number> =} callback
     **/
    currentIndex: GenericStorageQuery<() => number>;

    /**
     * True if the underlying economic identities or weighting behind the validators
     * has changed in the queued validator set.
     *
     * @param {Callback<boolean> =} callback
     **/
    queuedChanged: GenericStorageQuery<() => boolean>;

    /**
     * The queued keys for the next session. When the next session begins, these keys
     * will be used to determine the validator's session keys.
     *
     * @param {Callback<Array<[AccountId32, ParachainTemplateRuntimeSessionKeys]>> =} callback
     **/
    queuedKeys: GenericStorageQuery<
      () => Array<[AccountId32, ParachainTemplateRuntimeSessionKeys]>
    >;

    /**
     * Indices of disabled validators.
     *
     * The vec is always kept sorted so that we can find whether a given validator is
     * disabled using binary search. It gets cleared when `on_session_ending` returns
     * a new set of identities.
     *
     * @param {Callback<Array<[number, SpStakingOffenceOffenceSeverity]>> =} callback
     **/
    disabledValidators: GenericStorageQuery<
      () => Array<[number, SpStakingOffenceOffenceSeverity]>
    >;

    /**
     * The next session keys for a validator.
     *
     * @param {AccountId32Like} arg
     * @param {Callback<ParachainTemplateRuntimeSessionKeys | undefined> =} callback
     **/
    nextKeys: GenericStorageQuery<
      (arg: AccountId32Like) => ParachainTemplateRuntimeSessionKeys | undefined,
      AccountId32
    >;

    /**
     * The owner of a key. The key is the `KeyTypeId` + the encoded key.
     *
     * @param {[SpCoreCryptoKeyTypeId, BytesLike]} arg
     * @param {Callback<AccountId32 | undefined> =} callback
     **/
    keyOwner: GenericStorageQuery<
      (arg: [SpCoreCryptoKeyTypeId, BytesLike]) => AccountId32 | undefined,
      [SpCoreCryptoKeyTypeId, Bytes]
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Aura`'s storage queries
   **/
  aura: {
    /**
     * The current authority set.
     *
     * @param {Callback<Array<SpConsensusAuraSr25519AppSr25519Public>> =} callback
     **/
    authorities: GenericStorageQuery<
      () => Array<SpConsensusAuraSr25519AppSr25519Public>
    >;

    /**
     * The current slot of this block.
     *
     * This will be set in `on_initialize`.
     *
     * @param {Callback<SpConsensusSlotsSlot> =} callback
     **/
    currentSlot: GenericStorageQuery<() => SpConsensusSlotsSlot>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `AuraExt`'s storage queries
   **/
  auraExt: {
    /**
     * Serves as cache for the authorities.
     *
     * The authorities in AuRa are overwritten in `on_initialize` when we switch to a new session,
     * but we require the old authorities to verify the seal when validating a PoV. This will
     * always be updated to the latest AuRa authorities in `on_finalize`.
     *
     * @param {Callback<Array<SpConsensusAuraSr25519AppSr25519Public>> =} callback
     **/
    authorities: GenericStorageQuery<
      () => Array<SpConsensusAuraSr25519AppSr25519Public>
    >;

    /**
     * Current relay chain slot paired with a number of authored blocks.
     *
     * This is updated in [`FixedVelocityConsensusHook::on_state_proof`] with the current relay
     * chain slot as provided by the relay chain state proof.
     *
     * @param {Callback<[SpConsensusSlotsSlot, number] | undefined> =} callback
     **/
    relaySlotInfo: GenericStorageQuery<
      () => [SpConsensusSlotsSlot, number] | undefined
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `XcmpQueue`'s storage queries
   **/
  xcmpQueue: {
    /**
     * The suspended inbound XCMP channels. All others are not suspended.
     *
     * This is a `StorageValue` instead of a `StorageMap` since we expect multiple reads per block
     * to different keys with a one byte payload. The access to `BoundedBTreeSet` will be cached
     * within the block and therefore only included once in the proof size.
     *
     * NOTE: The PoV benchmarking cannot know this and will over-estimate, but the actual proof
     * will be smaller.
     *
     * @param {Callback<Array<PolkadotParachainPrimitivesPrimitivesId>> =} callback
     **/
    inboundXcmpSuspended: GenericStorageQuery<
      () => Array<PolkadotParachainPrimitivesPrimitivesId>
    >;

    /**
     * The non-empty XCMP channels in order of becoming non-empty, and the index of the first
     * and last outbound message. If the two indices are equal, then it indicates an empty
     * queue and there must be a non-`Ok` `OutboundStatus`. We assume queues grow no greater
     * than 65535 items. Queue indices for normal messages begin at one; zero is reserved in
     * case of the need to send a high-priority signal message this block.
     * The bool is true if there is a signal message waiting to be sent.
     *
     * @param {Callback<Array<CumulusPalletXcmpQueueOutboundChannelDetails>> =} callback
     **/
    outboundXcmpStatus: GenericStorageQuery<
      () => Array<CumulusPalletXcmpQueueOutboundChannelDetails>
    >;

    /**
     * The messages outbound in a given XCMP channel.
     *
     * @param {[PolkadotParachainPrimitivesPrimitivesId, number]} arg
     * @param {Callback<Bytes> =} callback
     **/
    outboundXcmpMessages: GenericStorageQuery<
      (arg: [PolkadotParachainPrimitivesPrimitivesId, number]) => Bytes,
      [PolkadotParachainPrimitivesPrimitivesId, number]
    >;

    /**
     * Any signal messages waiting to be sent.
     *
     * @param {PolkadotParachainPrimitivesPrimitivesId} arg
     * @param {Callback<Bytes> =} callback
     **/
    signalMessages: GenericStorageQuery<
      (arg: PolkadotParachainPrimitivesPrimitivesId) => Bytes,
      PolkadotParachainPrimitivesPrimitivesId
    >;

    /**
     * The configuration which controls the dynamics of the outbound queue.
     *
     * @param {Callback<CumulusPalletXcmpQueueQueueConfigData> =} callback
     **/
    queueConfig: GenericStorageQuery<
      () => CumulusPalletXcmpQueueQueueConfigData
    >;

    /**
     * Whether or not the XCMP queue is suspended from executing incoming XCMs or not.
     *
     * @param {Callback<boolean> =} callback
     **/
    queueSuspended: GenericStorageQuery<() => boolean>;

    /**
     * The factor to multiply the base delivery fee by.
     *
     * @param {PolkadotParachainPrimitivesPrimitivesId} arg
     * @param {Callback<FixedU128> =} callback
     **/
    deliveryFeeFactor: GenericStorageQuery<
      (arg: PolkadotParachainPrimitivesPrimitivesId) => FixedU128,
      PolkadotParachainPrimitivesPrimitivesId
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `PolkadotXcm`'s storage queries
   **/
  polkadotXcm: {
    /**
     * The latest available query index.
     *
     * @param {Callback<bigint> =} callback
     **/
    queryCounter: GenericStorageQuery<() => bigint>;

    /**
     * The ongoing queries.
     *
     * @param {bigint} arg
     * @param {Callback<PalletXcmQueryStatus | undefined> =} callback
     **/
    queries: GenericStorageQuery<
      (arg: bigint) => PalletXcmQueryStatus | undefined,
      bigint
    >;

    /**
     * The existing asset traps.
     *
     * Key is the blake2 256 hash of (origin, versioned `Assets`) pair. Value is the number of
     * times this pair has been trapped (usually just 1 if it exists at all).
     *
     * @param {H256} arg
     * @param {Callback<number> =} callback
     **/
    assetTraps: GenericStorageQuery<(arg: H256) => number, H256>;

    /**
     * Default version to encode XCM when latest version of destination is unknown. If `None`,
     * then the destinations whose XCM version is unknown are considered unreachable.
     *
     * @param {Callback<number | undefined> =} callback
     **/
    safeXcmVersion: GenericStorageQuery<() => number | undefined>;

    /**
     * The Latest versions that we know various locations support.
     *
     * @param {[number, XcmVersionedLocation]} arg
     * @param {Callback<number | undefined> =} callback
     **/
    supportedVersion: GenericStorageQuery<
      (arg: [number, XcmVersionedLocation]) => number | undefined,
      [number, XcmVersionedLocation]
    >;

    /**
     * All locations that we have requested version notifications from.
     *
     * @param {[number, XcmVersionedLocation]} arg
     * @param {Callback<bigint | undefined> =} callback
     **/
    versionNotifiers: GenericStorageQuery<
      (arg: [number, XcmVersionedLocation]) => bigint | undefined,
      [number, XcmVersionedLocation]
    >;

    /**
     * The target locations that are subscribed to our version changes, as well as the most recent
     * of our versions we informed them of.
     *
     * @param {[number, XcmVersionedLocation]} arg
     * @param {Callback<[bigint, SpWeightsWeightV2Weight, number] | undefined> =} callback
     **/
    versionNotifyTargets: GenericStorageQuery<
      (
        arg: [number, XcmVersionedLocation],
      ) => [bigint, SpWeightsWeightV2Weight, number] | undefined,
      [number, XcmVersionedLocation]
    >;

    /**
     * Destinations whose latest XCM version we would like to know. Duplicates not allowed, and
     * the `u32` counter is the number of times that a send to the destination has been attempted,
     * which is used as a prioritization.
     *
     * @param {Callback<Array<[XcmVersionedLocation, number]>> =} callback
     **/
    versionDiscoveryQueue: GenericStorageQuery<
      () => Array<[XcmVersionedLocation, number]>
    >;

    /**
     * The current migration's stage, if any.
     *
     * @param {Callback<PalletXcmVersionMigrationStage | undefined> =} callback
     **/
    currentMigration: GenericStorageQuery<
      () => PalletXcmVersionMigrationStage | undefined
    >;

    /**
     * Fungible assets which we know are locked on a remote chain.
     *
     * @param {[number, AccountId32Like, XcmVersionedAssetId]} arg
     * @param {Callback<PalletXcmRemoteLockedFungibleRecord | undefined> =} callback
     **/
    remoteLockedFungibles: GenericStorageQuery<
      (
        arg: [number, AccountId32Like, XcmVersionedAssetId],
      ) => PalletXcmRemoteLockedFungibleRecord | undefined,
      [number, AccountId32, XcmVersionedAssetId]
    >;

    /**
     * Fungible assets which we know are locked on this chain.
     *
     * @param {AccountId32Like} arg
     * @param {Callback<Array<[bigint, XcmVersionedLocation]> | undefined> =} callback
     **/
    lockedFungibles: GenericStorageQuery<
      (
        arg: AccountId32Like,
      ) => Array<[bigint, XcmVersionedLocation]> | undefined,
      AccountId32
    >;

    /**
     * Global suspension state of the XCM executor.
     *
     * @param {Callback<boolean> =} callback
     **/
    xcmExecutionSuspended: GenericStorageQuery<() => boolean>;

    /**
     * Whether or not incoming XCMs (both executed locally and received) should be recorded.
     * Only one XCM program will be recorded at a time.
     * This is meant to be used in runtime APIs, and it's advised it stays false
     * for all other use cases, so as to not degrade regular performance.
     *
     * Only relevant if this pallet is being used as the [`xcm_executor::traits::RecordXcm`]
     * implementation in the XCM executor configuration.
     *
     * @param {Callback<boolean> =} callback
     **/
    shouldRecordXcm: GenericStorageQuery<() => boolean>;

    /**
     * If [`ShouldRecordXcm`] is set to true, then the last XCM program executed locally
     * will be stored here.
     * Runtime APIs can fetch the XCM that was executed by accessing this value.
     *
     * Only relevant if this pallet is being used as the [`xcm_executor::traits::RecordXcm`]
     * implementation in the XCM executor configuration.
     *
     * @param {Callback<StagingXcmV5Xcm | undefined> =} callback
     **/
    recordedXcm: GenericStorageQuery<() => StagingXcmV5Xcm | undefined>;

    /**
     * Map of authorized aliasers of local origins. Each local location can authorize a list of
     * other locations to alias into it. Each aliaser is only valid until its inner `expiry`
     * block number.
     *
     * @param {XcmVersionedLocation} arg
     * @param {Callback<PalletXcmAuthorizedAliasesEntry | undefined> =} callback
     **/
    authorizedAliases: GenericStorageQuery<
      (
        arg: XcmVersionedLocation,
      ) => PalletXcmAuthorizedAliasesEntry | undefined,
      XcmVersionedLocation
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `MessageQueue`'s storage queries
   **/
  messageQueue: {
    /**
     * The index of the first and last (non-empty) pages.
     *
     * @param {CumulusPrimitivesCoreAggregateMessageOrigin} arg
     * @param {Callback<PalletMessageQueueBookState> =} callback
     **/
    bookStateFor: GenericStorageQuery<
      (
        arg: CumulusPrimitivesCoreAggregateMessageOrigin,
      ) => PalletMessageQueueBookState,
      CumulusPrimitivesCoreAggregateMessageOrigin
    >;

    /**
     * The origin at which we should begin servicing.
     *
     * @param {Callback<CumulusPrimitivesCoreAggregateMessageOrigin | undefined> =} callback
     **/
    serviceHead: GenericStorageQuery<
      () => CumulusPrimitivesCoreAggregateMessageOrigin | undefined
    >;

    /**
     * The map of page indices to pages.
     *
     * @param {[CumulusPrimitivesCoreAggregateMessageOrigin, number]} arg
     * @param {Callback<PalletMessageQueuePage | undefined> =} callback
     **/
    pages: GenericStorageQuery<
      (
        arg: [CumulusPrimitivesCoreAggregateMessageOrigin, number],
      ) => PalletMessageQueuePage | undefined,
      [CumulusPrimitivesCoreAggregateMessageOrigin, number]
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `TemplatePallet`'s storage queries
   **/
  templatePallet: {
    /**
     * The pallet's storage items.
     * <https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/your_first_pallet/index.html#storage>
     * <https://paritytech.github.io/polkadot-sdk/master/frame_support/pallet_macros/attr.storage.html>
     *
     * @param {Callback<PalletParachainTemplateCompositeStruct | undefined> =} callback
     **/
    something: GenericStorageQuery<
      () => PalletParachainTemplateCompositeStruct | undefined
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Keyword`'s storage queries
   **/
  keyword: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletKeywordKeywordRecord | undefined> =} callback
     **/
    keywords: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletKeywordKeywordRecord | undefined,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Skill`'s storage queries
   **/
  skill: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletSkillSkillRecord | undefined> =} callback
     **/
    skills: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletSkillSkillRecord | undefined,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Faction`'s storage queries
   **/
  faction: {
    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<PalletFactionFactionRecord | undefined> =} callback
     **/
    factions: GenericStorageQuery<
      (arg: FixedBytes<16>) => PalletFactionFactionRecord | undefined,
      FixedBytes<16>
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<FixedBytes<16> | undefined> =} callback
     **/
    variantOf: GenericStorageQuery<
      (arg: FixedBytes<16>) => FixedBytes<16> | undefined,
      FixedBytes<16>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Battlekit`'s storage queries
   **/
  battlekit: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletBattlekitItemRecord | undefined> =} callback
     **/
    items: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletBattlekitItemRecord | undefined,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Armoury`'s storage queries
   **/
  armoury: {
    /**
     *
     * @param {[FixedBytes<16>, FixedBytes<32>]} arg
     * @param {Callback<PalletArmouryArmouryEntryDef | undefined> =} callback
     **/
    entries: GenericStorageQuery<
      (
        arg: [FixedBytes<16>, FixedBytes<32>],
      ) => PalletArmouryArmouryEntryDef | undefined,
      [FixedBytes<16>, FixedBytes<32>]
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<Array<FixedBytes<32>>> =} callback
     **/
    factionItems: GenericStorageQuery<
      (arg: FixedBytes<16>) => Array<FixedBytes<32>>,
      FixedBytes<16>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Entry`'s storage queries
   **/
  entry: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletEntryEntryRecord | undefined> =} callback
     **/
    entries: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletEntryEntryRecord | undefined,
      FixedBytes<32>
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<Array<FixedBytes<32>>> =} callback
     **/
    factionEntries: GenericStorageQuery<
      (arg: FixedBytes<16>) => Array<FixedBytes<32>>,
      FixedBytes<16>
    >;

    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<PalletEntryAbilityDef>> =} callback
     **/
    entryAbilities: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<PalletEntryAbilityDef>,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Patron`'s storage queries
   **/
  patron: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletPatronPatronRecord | undefined> =} callback
     **/
    patrons: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletPatronPatronRecord | undefined,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Warband`'s storage queries
   **/
  warband: {
    /**
     *
     * @param {Callback<number> =} callback
     **/
    nextWarbandId: GenericStorageQuery<() => number>;

    /**
     *
     * @param {number} arg
     * @param {Callback<PalletWarbandWarbandMeta | undefined> =} callback
     **/
    warbands: GenericStorageQuery<
      (arg: number) => PalletWarbandWarbandMeta | undefined,
      number
    >;

    /**
     *
     * @param {AccountId32Like} arg
     * @param {Callback<Array<number>> =} callback
     **/
    ownerWarbands: GenericStorageQuery<
      (arg: AccountId32Like) => Array<number>,
      AccountId32
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Roster`'s storage queries
   **/
  roster: {
    /**
     *
     * @param {number} arg
     * @param {Callback<Array<PalletRosterRecruit>> =} callback
     **/
    roster: GenericStorageQuery<
      (arg: number) => Array<PalletRosterRecruit>,
      number
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Campaign`'s storage queries
   **/
  campaign: {
    /**
     *
     * @param {Callback<number> =} callback
     **/
    nextCampaignId: GenericStorageQuery<() => number>;

    /**
     *
     * @param {number} arg
     * @param {Callback<PalletCampaignCampaignMeta | undefined> =} callback
     **/
    campaigns: GenericStorageQuery<
      (arg: number) => PalletCampaignCampaignMeta | undefined,
      number
    >;

    /**
     *
     * @param {number} arg
     * @param {Callback<Array<number>> =} callback
     **/
    enrollments: GenericStorageQuery<(arg: number) => Array<number>, number>;

    /**
     * VP score per warband in a campaign.
     *
     * @param {[number, number]} arg
     * @param {Callback<number> =} callback
     **/
    scores: GenericStorageQuery<
      (arg: [number, number]) => number,
      [number, number]
    >;

    /**
     * Eliminated warbands in a campaign.
     *
     * @param {number} arg
     * @param {Callback<Array<number>> =} callback
     **/
    eliminated: GenericStorageQuery<(arg: number) => Array<number>, number>;

    /**
     * Team assignment per warband (0 = FFA/no team, 1+ = team index).
     *
     * @param {[number, number]} arg
     * @param {Callback<number> =} callback
     **/
    teams: GenericStorageQuery<
      (arg: [number, number]) => number,
      [number, number]
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Battle`'s storage queries
   **/
  battle: {
    /**
     *
     * @param {Callback<number> =} callback
     **/
    nextBattleId: GenericStorageQuery<() => number>;

    /**
     *
     * @param {number} arg
     * @param {Callback<PalletBattleBattleMeta | undefined> =} callback
     **/
    battles: GenericStorageQuery<
      (arg: number) => PalletBattleBattleMeta | undefined,
      number
    >;

    /**
     *
     * @param {number} arg
     * @param {Callback<number | undefined> =} callback
     **/
    warbandActiveBattle: GenericStorageQuery<
      (arg: number) => number | undefined,
      number
    >;

    /**
     *
     * @param {[number, number]} arg
     * @param {Callback<PalletBattleBattleReport | undefined> =} callback
     **/
    reports: GenericStorageQuery<
      (arg: [number, number]) => PalletBattleBattleReport | undefined,
      [number, number]
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Territory`'s storage queries
   **/
  territory: {
    /**
     *
     * @param {[number, FixedBytes<32>]} arg
     * @param {Callback<PalletTerritoryTerritoryState | undefined> =} callback
     **/
    territories: GenericStorageQuery<
      (
        arg: [number, FixedBytes<32>],
      ) => PalletTerritoryTerritoryState | undefined,
      [number, FixedBytes<32>]
    >;

    /**
     *
     * @param {[number, FixedBytes<32>]} arg
     * @param {Callback<Array<FixedBytes<32>>> =} callback
     **/
    buildings: GenericStorageQuery<
      (arg: [number, FixedBytes<32>]) => Array<FixedBytes<32>>,
      [number, FixedBytes<32>]
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Building`'s storage queries
   **/
  building: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletBuildingBuildingDef | undefined> =} callback
     **/
    buildingDefs: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletBuildingBuildingDef | undefined,
      FixedBytes<32>
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<PalletBuildingResourceDef | undefined> =} callback
     **/
    resources: GenericStorageQuery<
      (arg: FixedBytes<16>) => PalletBuildingResourceDef | undefined,
      FixedBytes<16>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Exploration`'s storage queries
   **/
  exploration: {
    /**
     *
     * @param {[number, number]} arg
     * @param {Callback<PalletExplorationExplorationOutcome | undefined> =} callback
     **/
    explorationResults: GenericStorageQuery<
      (
        arg: [number, number],
      ) => PalletExplorationExplorationOutcome | undefined,
      [number, number]
    >;

    /**
     *
     * @param {number} arg
     * @param {Callback<Array<number>> =} callback
     **/
    discoveryLog: GenericStorageQuery<(arg: number) => Array<number>, number>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Tile`'s storage queries
   **/
  tile: {
    /**
     *
     * @param {[number, number]} arg
     * @param {Callback<PalletTileTileCompact | undefined> =} callback
     **/
    tiles: GenericStorageQuery<
      (arg: [number, number]) => PalletTileTileCompact | undefined,
      [number, number]
    >;

    /**
     *
     * @param {Callback<number> =} callback
     **/
    tileCount: GenericStorageQuery<() => number>;

    /**
     *
     * @param {number} arg
     * @param {Callback<PalletTileTerrainMeta | undefined> =} callback
     **/
    terrainRegistry: GenericStorageQuery<
      (arg: number) => PalletTileTerrainMeta | undefined,
      number
    >;

    /**
     *
     * @param {Callback<PalletTileMapConfig | undefined> =} callback
     **/
    config: GenericStorageQuery<() => PalletTileMapConfig | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Region`'s storage queries
   **/
  region: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletRegionRegionDef | undefined> =} callback
     **/
    regions: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletRegionRegionDef | undefined,
      FixedBytes<32>
    >;

    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<[number, number]> | undefined> =} callback
     **/
    regionTiles: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<[number, number]> | undefined,
      FixedBytes<32>
    >;

    /**
     *
     * @param {[FixedBytes<32>, [number, number]]} arg
     * @param {Callback<TcPrimitivesAlignment | undefined> =} callback
     **/
    regionTileControl: GenericStorageQuery<
      (
        arg: [FixedBytes<32>, [number, number]],
      ) => TcPrimitivesAlignment | undefined,
      [FixedBytes<32>, [number, number]]
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Country`'s storage queries
   **/
  country: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletCountryCountryDef | undefined> =} callback
     **/
    countries: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletCountryCountryDef | undefined,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Poi`'s storage queries
   **/
  poi: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletPoiPoiDef | undefined> =} callback
     **/
    pois: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletPoiPoiDef | undefined,
      FixedBytes<32>
    >;

    /**
     *
     * @param {Callback<number> =} callback
     **/
    poiCount: GenericStorageQuery<() => number>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Theatre`'s storage queries
   **/
  theatre: {
    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletTheatreTheatreDef | undefined> =} callback
     **/
    theatres: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletTheatreTheatreDef | undefined,
      FixedBytes<32>
    >;

    /**
     * Regions composing this theatre (the map = union of all tiles in these regions).
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<FixedBytes<32>>> =} callback
     **/
    theatreRegions: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<FixedBytes<32>>,
      FixedBytes<32>
    >;

    /**
     * Objectives for this theatre.
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletTheatreObjectiveSet | undefined> =} callback
     **/
    theatreObjectives: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletTheatreObjectiveSet | undefined,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Equiprules`'s storage queries
   **/
  equiprules: {
    /**
     *
     * @param {Callback<number> =} callback
     **/
    handSlots: GenericStorageQuery<() => number>;

    /**
     *
     * @param {TcPrimitivesBattlekitType} arg
     * @param {Callback<PalletEquiprulesSlotRule | undefined> =} callback
     **/
    slotRules: GenericStorageQuery<
      (arg: TcPrimitivesBattlekitType) => PalletEquiprulesSlotRule | undefined,
      TcPrimitivesBattlekitType
    >;

    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletEquiprulesTagDef | undefined> =} callback
     **/
    tags: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletEquiprulesTagDef | undefined,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `CampaignRules`'s storage queries
   **/
  campaignRules: {
    /**
     *
     * @param {Callback<Array<PalletCampaignRulesThresholdRow>> =} callback
     **/
    thresholdTable: GenericStorageQuery<
      () => Array<PalletCampaignRulesThresholdRow>
    >;

    /**
     *
     * @param {Callback<PalletCampaignRulesVictoryConfig | undefined> =} callback
     **/
    victory: GenericStorageQuery<
      () => PalletCampaignRulesVictoryConfig | undefined
    >;

    /**
     *
     * @param {Callback<Array<PalletCampaignRulesTraumaRow>> =} callback
     **/
    traumaTable: GenericStorageQuery<() => Array<PalletCampaignRulesTraumaRow>>;

    /**
     *
     * @param {Callback<Array<PalletCampaignRulesPhaseStep>> =} callback
     **/
    phaseSteps: GenericStorageQuery<() => Array<PalletCampaignRulesPhaseStep>>;

    /**
     *
     * @param {Callback<PalletCampaignRulesPromotionRules | undefined> =} callback
     **/
    promotions: GenericStorageQuery<
      () => PalletCampaignRulesPromotionRules | undefined
    >;

    /**
     *
     * @param {Callback<Array<PalletCampaignRulesQuartermasterAction>> =} callback
     **/
    quartermasterActions: GenericStorageQuery<
      () => Array<PalletCampaignRulesQuartermasterAction>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `ExplorationRules`'s storage queries
   **/
  explorationRules: {
    /**
     *
     * @param {Callback<Array<PalletExplorationRulesDiceProgressionRow>> =} callback
     **/
    diceProgression: GenericStorageQuery<
      () => Array<PalletExplorationRulesDiceProgressionRow>
    >;

    /**
     *
     * @param {Callback<Array<PalletExplorationRulesTableProgressionRow>> =} callback
     **/
    tableProgression: GenericStorageQuery<
      () => Array<PalletExplorationRulesTableProgressionRow>
    >;

    /**
     *
     * @param {Callback<number> =} callback
     **/
    lootMultiplier: GenericStorageQuery<() => number>;

    /**
     *
     * @param {Callback<number> =} callback
     **/
    rerollsBase: GenericStorageQuery<() => number>;

    /**
     *
     * @param {Callback<number> =} callback
     **/
    rerollsBonusIfWon: GenericStorageQuery<() => number>;

    /**
     *
     * @param {[TcPrimitivesExplorationTable, number]} arg
     * @param {Callback<PalletExplorationRulesExplorationEvent | undefined> =} callback
     **/
    events: GenericStorageQuery<
      (
        arg: [TcPrimitivesExplorationTable, number],
      ) => PalletExplorationRulesExplorationEvent | undefined,
      [TcPrimitivesExplorationTable, number]
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<PalletExplorationRulesExplorationSkillDef | undefined> =} callback
     **/
    skills: GenericStorageQuery<
      (
        arg: FixedBytes<16>,
      ) => PalletExplorationRulesExplorationSkillDef | undefined,
      FixedBytes<16>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `TerrainRules`'s storage queries
   **/
  terrainRules: {
    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<PalletTerrainRulesTerrainCategory | undefined> =} callback
     **/
    categories: GenericStorageQuery<
      (arg: FixedBytes<16>) => PalletTerrainRulesTerrainCategory | undefined,
      FixedBytes<16>
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<PalletTerrainRulesTerrainPiece | undefined> =} callback
     **/
    pieces: GenericStorageQuery<
      (arg: FixedBytes<16>) => PalletTerrainRulesTerrainPiece | undefined,
      FixedBytes<16>
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<PalletTerrainRulesBattlefieldArchetype | undefined> =} callback
     **/
    archetypes: GenericStorageQuery<
      (
        arg: FixedBytes<16>,
      ) => PalletTerrainRulesBattlefieldArchetype | undefined,
      FixedBytes<16>
    >;

    /**
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<Array<FixedBytes<16>>> =} callback
     **/
    terrainBattlefields: GenericStorageQuery<
      (arg: FixedBytes<16>) => Array<FixedBytes<16>>,
      FixedBytes<16>
    >;

    /**
     *
     * @param {Callback<PalletTerrainRulesCombatModifierConfig | undefined> =} callback
     **/
    combatModifiers: GenericStorageQuery<
      () => PalletTerrainRulesCombatModifierConfig | undefined
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Production`'s storage queries
   **/
  production: {
    /**
     * Buildings placed on tiles, indexed by region for fast prefix iteration.
     *
     * @param {[FixedBytes<32>, [number, number]]} arg
     * @param {Callback<Array<[FixedBytes<32>, number]>> =} callback
     **/
    tileBuildings: GenericStorageQuery<
      (
        arg: [FixedBytes<32>, [number, number]],
      ) => Array<[FixedBytes<32>, number]>,
      [FixedBytes<32>, [number, number]]
    >;

    /**
     * Passive terrain yields (seeded reference data).
     *
     * @param {number} arg
     * @param {Callback<Array<[FixedBytes<16>, number]>> =} callback
     **/
    terrainYields: GenericStorageQuery<
      (arg: number) => Array<[FixedBytes<16>, number]>,
      number
    >;

    /**
     * Transformation recipes per building type (seeded reference data).
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletProductionRecipeStorage | undefined> =} callback
     **/
    recipes: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletProductionRecipeStorage | undefined,
      FixedBytes<32>
    >;

    /**
     * Pre-computed base production per region (sum of all terrain yields).
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<[FixedBytes<16>, number]>> =} callback
     **/
    regionBaseProduction: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<[FixedBytes<16>, number]>,
      FixedBytes<32>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Demand`'s storage queries
   **/
  demand: {
    /**
     * Per-region demand (qty needed per turn).
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<[FixedBytes<16>, number]>> =} callback
     **/
    regionDemand: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<[FixedBytes<16>, number]>,
      FixedBytes<32>
    >;

    /**
     * Base demand inherited by all regions of a faction.
     *
     * @param {FixedBytes<16>} arg
     * @param {Callback<Array<[FixedBytes<16>, number]>> =} callback
     **/
    factionBaseDemand: GenericStorageQuery<
      (arg: FixedBytes<16>) => Array<[FixedBytes<16>, number]>,
      FixedBytes<16>
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Logistics`'s storage queries
   **/
  logistics: {
    /**
     * All known region codes (seeded, used for iteration).
     *
     * @param {Callback<Array<FixedBytes<32>>> =} callback
     **/
    knownRegions: GenericStorageQuery<() => Array<FixedBytes<32>>>;

    /**
     * Current resource stock per region.
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<[FixedBytes<16>, number]>> =} callback
     **/
    regionStock: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<[FixedBytes<16>, number]>,
      FixedBytes<32>
    >;

    /**
     * Minimum stock threshold before a region can export.
     *
     * @param {[FixedBytes<32>, FixedBytes<16>]} arg
     * @param {Callback<number> =} callback
     **/
    minStock: GenericStorageQuery<
      (arg: [FixedBytes<32>, FixedBytes<16>]) => number,
      [FixedBytes<32>, FixedBytes<16>]
    >;

    /**
     * Resource packets currently in transit within a region.
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<PalletLogisticsPacket>> =} callback
     **/
    inTransit: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<PalletLogisticsPacket>,
      FixedBytes<32>
    >;

    /**
     * Region adjacency graph (seeded).
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<Array<FixedBytes<32>>> =} callback
     **/
    regionAdjacency: GenericStorageQuery<
      (arg: FixedBytes<32>) => Array<FixedBytes<32>>,
      FixedBytes<32>
    >;

    /**
     * Pre-computed distances between region pairs (BFS hops, seeded).
     *
     * @param {[FixedBytes<32>, FixedBytes<32>]} arg
     * @param {Callback<number> =} callback
     **/
    regionDistances: GenericStorageQuery<
      (arg: [FixedBytes<32>, FixedBytes<32>]) => number,
      [FixedBytes<32>, FixedBytes<32>]
    >;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
}
